// Drizzle ORM database client — Turso (libsql) in production, local SQLite in dev.
// ─────────────────────────────────────────────────────────────────────────────
// Exports:
//   - `getDb()` — async getter that returns the initialized Drizzle instance.
//                 API routes do `const db = await getDb();` then use `db.select(...)` etc.
//   - `dbReady` — the init promise (resolved when the DB is ready + migrations applied).
//
// Provider selection (in priority order):
//   1. TURSO_DATABASE_URL + TURSO_AUTH_TOKEN  → Turso (libsql) — production
//   2. DATABASE_URL=file:./db/custom.db        → local better-sqlite3 — dev
//   3. No env vars                               → local better-sqlite3 — dev fallback
//
// Schema management:
//   - Migrations are generated by `drizzle-kit generate` and stored in ./drizzle/
//   - On first DB connection, `migrate()` from drizzle-orm/{libsql|better-sqlite3}/migrator
//     runs all pending migrations and tracks applied state in a `__drizzle_migrations`
//     table. This is the standard Drizzle approach — single source of truth in
//     schema.ts, versioned migration files, no schema drift.
//   - To add a column/table: edit schema.ts, run `bun run db:generate`, commit
//     the new migration file. The app applies it automatically on next deploy.
//
// The client is cached on `globalThis` so Next.js hot-reload doesn't open a
// new connection on every code change.

import { mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { savedCircuits } from './schema';

// ─────────────────────────────────────────────────────────────────────────────
// Provider selection — read env vars lazily so tests can override them.
// ─────────────────────────────────────────────────────────────────────────────

function getTursoUrl() { return process.env.TURSO_DATABASE_URL; }
function getTursoToken() { return process.env.TURSO_AUTH_TOKEN; }
function useTurso() { return !!getTursoUrl() && !!getTursoToken(); }
function getLocalDbPath() {
  const raw = (process.env.DATABASE_URL ?? 'file:./db/custom.db').replace(/^file:/, '');
  if (!raw.startsWith('/')) {
    return `${process.cwd()}/${raw.replace(/^\.\//, '')}`;
  }
  return raw;
}

// Migrations folder — relative to the project root. Must be bundled with the
// deployment (Vercel includes all non-ignored files by default).
const MIGRATIONS_FOLDER = resolve(process.cwd(), 'drizzle');

const globalForDb = globalThis as unknown as {
  __drizzleDb: any | undefined;
  __sqliteInstance: any | undefined;
  __dbPromise: Promise<any> | undefined;
  __shutdownRegistered: boolean | undefined;
};

async function createDb() {
  // During `next build`, Next.js evaluates route modules to collect page data.
  // Skip DB connection at build time — the real DB is only needed at runtime.
  if (process.env.NEXT_BUILD === 'true' || process.env.NEXT_PHASE === 'phase-production-build') {
    return { stub: true } as any;
  }

  if (useTurso()) {
    // ── Turso (libsql) — production ──────────────────────────────────────
    const { createClient } = await import('@libsql/client');
    const { drizzle } = await import('drizzle-orm/libsql');
    const { migrate } = await import('drizzle-orm/libsql/migrator');
    const client = createClient({
      url: getTursoUrl()!,
      authToken: getTursoToken()!,
    });
    const db = drizzle(client, { schema: { savedCircuits } });
    // Run pending migrations — creates the schema if missing, applies any
    // new migrations added in future deploys. Idempotent: tracks applied
    // migrations in the `__drizzle_migrations` table.
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
    globalForDb.__sqliteInstance = client;
    return db;
  }

  // ── Local better-sqlite3 — development ────────────────────────────────
  const localDbPath = getLocalDbPath();
  const Database = (await import('better-sqlite3')).default;
  const { drizzle } = await import('drizzle-orm/better-sqlite3');
  const { migrate } = await import('drizzle-orm/better-sqlite3/migrator');
  try {
    mkdirSync(dirname(localDbPath), { recursive: true });
  } catch {
    // Read-only env — let better-sqlite3 throw a descriptive error below.
  }
  const sqlite = new Database(localDbPath);
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  const db = drizzle(sqlite, { schema: { savedCircuits } });
  // Run pending migrations (sync for better-sqlite3).
  migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  globalForDb.__sqliteInstance = sqlite;
  return db;
}

// Init promise — cached on globalThis so hot-reload doesn't re-init.
// Re-evaluated by getDb() so tests can clear the cache.
function initDb(): Promise<any> {
  if (globalForDb.__dbPromise) return globalForDb.__dbPromise;
  const p = (async () => {
    if (globalForDb.__drizzleDb) return globalForDb.__drizzleDb;
    const db = await createDb();
    if (process.env.NODE_ENV !== 'production') {
      globalForDb.__drizzleDb = db;
    }
    return db;
  })();
  globalForDb.__dbPromise = p;
  return p;
}

// For backward compat — module-level export that triggers init on first import.
export const dbReady: Promise<any> = initDb();

/**
 * Get the initialized Drizzle DB instance. API routes should do:
 *   const db = await getDb();
 *   const rows = await db.select(...)...
 *
 * For local better-sqlite3 (dev), this resolves synchronously. For Turso
 * (production), this awaits the libsql client init + migration run (~10ms warm).
 */
export async function getDb(): Promise<any> {
  return initDb();
}

// Graceful shutdown — close the connection cleanly on process exit.
if (!globalForDb.__shutdownRegistered) {
  globalForDb.__shutdownRegistered = true;
  const shutdown = () => {
    try {
      globalForDb.__sqliteInstance?.close?.();
    } catch {
      // Ignore errors during shutdown
    }
    process.exit(0);
  };
  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);
}
