import { describe, it, expect, beforeAll } from 'vitest';
import { solveDC, simulateStep, buildNodeMap, computeComponentCurrents, computeWireCurrents } from '../src/lib/circuit/engine';
import { getPlugin, getAllPlugins } from '../src/lib/circuit/registry';
import { useEditor } from '../src/lib/circuit/store';
import { exportSPICENetlist } from '../src/lib/circuit/netlist-export';
import { importSpiceNetlist } from '../src/lib/circuit/spice-import';
import { saveCircuitDocument, loadCircuitDocument } from '../src/lib/circuit/migration';
import { saveToLocalStorage, loadFromLocalStorage } from '../src/lib/circuit/autosave';
import { annotateNets, findNetConflicts } from '../src/lib/circuit/net-annotation';
import { exampleTransistor, exampleOpamp } from '../src/lib/circuit/examples';
import type { CircuitComponent, Wire, CircuitDocument, ComponentPlugin } from '../src/lib/circuit/types';
beforeAll(async () => { await import('../src/lib/circuit/components/sources'); await import('../src/lib/circuit/components/passive'); await import('../src/lib/circuit/components/semiconductors'); await import('../src/lib/circuit/components/extra'); await import('../src/lib/circuit/components/advanced'); });
function comp(t:string,id:string,p?:any){const pl=getPlugin(t);const d:any={};if(pl)for(const pm of pl.parameters)d[pm.key]=pm.default;return{id,type:t,position:{x:0,y:0},rotation:0,parameters:{...d,...p},simState:{}};}
function wire(id:string,f:string,ft:string,t:string,tt:string){return{id,from:{componentId:f,terminalId:ft},to:{componentId:t,terminalId:tt}};}
function plugins(){return new Map(getAllPlugins().map(p=>[p.type,p]));}
describe('#3 State-machine fuzzing', () => { it('50 random actions: no crash', () => { const s=useEditor.getState();s.clear();s.reset();for(let i=0;i<50;i++){try{s.addComponent('resistor',{x:i,y:0});}catch{}if(i%10===0)s.undo();}expect(useEditor.getState().components.length).toBeGreaterThanOrEqual(0);});});
describe('#4 Round-trip', () => { it('JSON save/load', () => { const j=saveCircuitDocument(exampleTransistor);const r=loadCircuitDocument(j);expect(r.doc).not.toBeNull();expect(r.doc!.components.length).toBe(exampleTransistor.components.length);});it('localStorage save/load', () => { const m=new Map<string,string>();(globalThis as any).localStorage={getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>m.set(k,v),removeItem:(k:string)=>m.delete(k)};saveToLocalStorage('test',exampleTransistor);const l=loadFromLocalStorage('test');expect(l).not.toBeNull();expect(l!.components.length).toBe(exampleTransistor.components.length);});});
describe('#5 Numerical stress', () => { it('1 TΩ divider', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:1e12}),comp('resistor','R2',{resistance:1e12}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','R2','a'),wire('w3','R2','b','GND','g'),wire('w4','V1','n','GND','g')];const dc=solveDC(c,w,p);expect(dc).not.toBeNull();const nm=buildNodeMap(c,w,p);expect(dc!.nodeVoltage[nm.terminalNode.get('R1:b')!]).toBeCloseTo(2.5,1);});it('1 µΩ: no Infinity', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:1e-6}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','GND','g'),wire('w3','V1','n','GND','g')];const dc=solveDC(c,w,p);expect(dc).not.toBeNull();for(let i=0;i<dc!.nodeVoltage.length;i++)expect(isFinite(dc!.nodeVoltage[i])).toBe(true);});});
describe('#6 Transient continuity', () => { it('RC: monotonic charging', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:1000}),comp('capacitor','C1',{capacitance:1e-6}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','C1','a'),wire('w3','C1','b','GND','g'),wire('w4','V1','n','GND','g')];let prev:any;let pv=0;for(let i=0;i<100;i++){const r=simulateStep(c,w,p,prev,1e-4);if(!r)break;const nm=buildNodeMap(c,w,p);const v=r.sim.nodeVoltage[nm.terminalNode.get('C1:a')!];expect(v).toBeGreaterThanOrEqual(pv-0.01);pv=v;prev={nodeVoltage:r.sim.nodeVoltage,branchCurrent:r.sim.branchCurrent,time:r.sim.time,state:r.sim.state};}expect(pv).toBeGreaterThan(4.9);});});
describe('#7 Cross-validation', () => { it('Voltage divider', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:12}),comp('resistor','R1',{resistance:4000}),comp('resistor','R2',{resistance:8000}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','R2','a'),wire('w3','R2','b','GND','g'),wire('w4','V1','n','GND','g')];const dc=solveDC(c,w,p);expect(dc).not.toBeNull();const nm=buildNodeMap(c,w,p);expect(dc!.nodeVoltage[nm.terminalNode.get('R1:b')!]).toBeCloseTo(8,2);});});
describe('#8 Wire current sanity', () => { it('Series: same current', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:1000}),comp('resistor','R2',{resistance:1000}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','R2','a'),wire('w3','R2','b','GND','g'),wire('w4','V1','n','GND','g')];const dc=solveDC(c,w,p);if(!dc)return;const r=simulateStep(c,w,p,{nodeVoltage:dc.nodeVoltage,branchCurrent:dc.branchCurrent,time:0,state:dc.state},1e-4);if(!r)return;const wc=computeWireCurrents(c,w,p,r.sim);const i1=Math.abs(wc.get('w1')??0);const i2=Math.abs(wc.get('w2')??0);const i3=Math.abs(wc.get('w3')??0);const mx=Math.max(i1,i2,i3);if(mx>1e-12)expect((mx-Math.min(i1,i2,i3))/mx).toBeLessThan(0.05);});});
describe('#9 Net annotation', () => { it('Annotates all nets', () => { const p=plugins();const anns=annotateNets(exampleOpamp.components,exampleOpamp.wires,p);expect(anns.length).toBeGreaterThan(0);const gnd=anns.find(a=>a.nodeId===0);expect(gnd).toBeDefined();expect(gnd!.netName).toBe('GND');});});
describe('#10 AI safety', () => { it('Negative resistance: no crash', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:-1000}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','GND','g'),wire('w3','V1','n','GND','g')];expect(()=>solveDC(c,w,p)).not.toThrow();});it('100 components: no crash', () => { const p=plugins();const c:CircuitComponent[]=[comp('dcVoltage','V1',{voltage:5}),comp('ground','GND')];for(let i=0;i<100;i++)c.push(comp('resistor','R'+i,{resistance:1000}));const w:Wire[]=[wire('w0','V1','p','R0','a'),wire('wg','V1','n','GND','g')];for(let i=0;i<99;i++)w.push(wire('w'+(i+1),'R'+i,'b','R'+(i+1),'a'));w.push(wire('wf','R99','b','GND','g'));expect(()=>solveDC(c,w,p)).not.toThrow();});});
