import { describe, it, expect, beforeAll } from 'vitest';
import { solveDC, simulateStep, buildNodeMap } from '../src/lib/circuit/engine';
import { getPlugin, getAllPlugins } from '../src/lib/circuit/registry';
import type { CircuitComponent, Wire, ComponentPlugin } from '../src/lib/circuit/types';
beforeAll(async () => { await import('../src/lib/circuit/components/sources'); await import('../src/lib/circuit/components/passive'); await import('../src/lib/circuit/components/semiconductors'); await import('../src/lib/circuit/components/extra'); });
function comp(t:string,id:string,p?:any):CircuitComponent{const pl=getPlugin(t);const d:any={};if(pl)for(const pm of pl.parameters)d[pm.key]=pm.default;return{id,type:t,position:{x:0,y:0},rotation:0,parameters:{...d,...p},simState:{}};}
function wire(id:string,f:string,ft:string,t:string,tt:string):Wire{return{id,from:{componentId:f,terminalId:ft},to:{componentId:t,terminalId:tt}};}
function plugins():Map<string,ComponentPlugin>{return new Map(getAllPlugins().map(p=>[p.type,p]));}
function isFiniteNum(x:number):boolean{return typeof x==='number'&&isFinite(x);}
function expectAllFinite(sim:any,l:string){expect(sim,l+': should not be null').not.toBeNull();for(let i=0;i<sim.nodeVoltage.length;i++)expect(isFiniteNum(sim.nodeVoltage[i]),l+': V(node'+i+')='+sim.nodeVoltage[i]).toBe(true);}
describe('Convergence stress', () => {
  it('Two V sources in parallel with different V: null or finite', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('dcVoltage','V2',{voltage:3}),comp('resistor','R1',{resistance:1000}),comp('ground','GND')];const w=[wire('w1','V1','p','V2','p'),wire('w2','V1','p','R1','a'),wire('w3','R1','b','GND','g'),wire('w4','V1','n','GND','g'),wire('w5','V2','n','GND','g')];const dc=solveDC(c,w,p);if(dc)expectAllFinite(dc,'parallel V sources');});
  it('Floating node via capacitor: null or finite', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('capacitor','C1',{capacitance:1e-6}),comp('ground','GND')];const w=[wire('w1','V1','p','C1','a'),wire('w2','C1','b','GND','g'),wire('w3','V1','n','GND','g')];const dc=solveDC(c,w,p);if(dc)expectAllFinite(dc,'floating cap node');});
  it('No ground: null or finite', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:1000}),comp('resistor','R2',{resistance:1000})];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','R2','a'),wire('w3','R2','b','V1','n')];const dc=solveDC(c,w,p);if(dc)expectAllFinite(dc,'no ground');});
  it('Diode near threshold: converges', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:1000}),comp('diode','D1',{forwardV:0.7,onR:1}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','D1','a'),wire('w3','D1','k','GND','g'),wire('w4','V1','n','GND','g')];const dc=solveDC(c,w,p,50);expect(dc).not.toBeNull();expectAllFinite(dc!,'diode near threshold');});
  it('100-node ladder: solves < 5s', () => { const p=plugins();const c:CircuitComponent[]=[comp('dcVoltage','V1',{voltage:5}),comp('ground','GND')];for(let i=0;i<100;i++)c.push(comp('resistor','R'+i,{resistance:1000}));const w:Wire[]=[wire('w0','V1','p','R0','a'),wire('wg','V1','n','GND','g')];for(let i=0;i<99;i++)w.push(wire('w'+(i+1),'R'+i,'b','R'+(i+1),'a'));w.push(wire('wf','R99','b','GND','g'));const s=Date.now();const dc=solveDC(c,w,p);const e=Date.now()-s;expect(dc).not.toBeNull();expect(e).toBeLessThan(5000);});
  it('1000-step RC: no NaN, converges', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:1000}),comp('capacitor','C1',{capacitance:1e-6}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','C1','a'),wire('w3','C1','b','GND','g'),wire('w4','V1','n','GND','g')];let prev:any=undefined;let last=0;for(let i=0;i<1000;i++){const r=simulateStep(c,w,p,prev,1e-4);if(!r)break;for(let j=0;j<r.sim.nodeVoltage.length;j++)expect(isFiniteNum(r.sim.nodeVoltage[j])).toBe(true);last=r.sim.nodeVoltage[r.sim.nodeVoltage.length-1]??0;prev={nodeVoltage:r.sim.nodeVoltage,branchCurrent:r.sim.branchCurrent,time:r.sim.time,state:r.sim.state};}expect(last).toBeGreaterThan(4.9);});
});
