import { describe, it, expect, beforeAll } from 'vitest';
import { solveDC, simulateStep, buildNodeMap, computeComponentCurrents, computeWireCurrents, getTerminalsForComponent } from '../src/lib/circuit/engine';
import { getPlugin, getAllPlugins } from '../src/lib/circuit/registry';
import { exampleTransistor, exampleOpamp, exampleLogicGates, exampleCurrentSource, example555, exampleArduino } from '../src/lib/circuit/examples';
import type { CircuitDocument, ComponentPlugin } from '../src/lib/circuit/types';
beforeAll(async () => { await import('../src/lib/circuit/components/sources'); await import('../src/lib/circuit/components/passive'); await import('../src/lib/circuit/components/semiconductors'); await import('../src/lib/circuit/components/extra'); await import('../src/lib/circuit/components/advanced'); await import('../src/lib/circuit/components/advanced-semi'); await import('../src/lib/circuit/components/advanced-devices'); });
function plugins():Map<string,ComponentPlugin>{return new Map(getAllPlugins().map(p=>[p.type,p]));}
const CIRCS:Array<{name:string;doc:CircuitDocument}>=[{name:'Transistor',doc:exampleTransistor},{name:'Opamp',doc:exampleOpamp},{name:'LogicGates',doc:exampleLogicGates},{name:'CurrentSource',doc:exampleCurrentSource},{name:'555',doc:example555},{name:'Arduino',doc:exampleArduino}];
describe('Property: finite voltages', () => { for(const{name,doc}of CIRCS){it(name+': no NaN',()=>{const dc=solveDC(doc.components,doc.wires,plugins());if(!dc)return;for(let i=0;i<dc.nodeVoltage.length;i++)expect(isFinite(dc.nodeVoltage[i])).toBe(true);});}});
describe('Property: Ohm law for resistors', () => { for(const{name,doc}of CIRCS){it(name+': V=IR',()=>{const p=plugins();const dc=solveDC(doc.components,doc.wires,p);if(!dc)return;const nm=buildNodeMap(doc.components,doc.wires,p);for(const c of doc.components){if(c.type!=='resistor')continue;const pl=p.get('resistor')!;const t=getTerminalsForComponent(c,pl,nm);const a=t.find(x=>x.terminalId==='a')?.nodeId??0;const b=t.find(x=>x.terminalId==='b')?.nodeId??0;const r=Math.max(1e-9,c.parameters.resistance as number);const v=(dc.nodeVoltage[a]??0)-(dc.nodeVoltage[b]??0);const i=v/r;const cc=computeComponentCurrents(doc.components,doc.wires,p,dc);const ai=cc.get(c.id)??0;const re=Math.abs(ai-i)/Math.max(Math.abs(i),1e-12);expect(re,name+': Ohm '+c.id).toBeLessThan(0.01);}});}});
describe('Property: rail bounds', () => { for(const{name,doc}of CIRCS){it(name+': V within rails',()=>{const dc=solveDC(doc.components,doc.wires,plugins());if(!dc)return;let maxRail=0;for(const c of doc.components){if(c.type==='dcVoltage')maxRail=Math.max(maxRail,Math.abs(c.parameters.voltage as number??0));}for(let i=0;i<dc.nodeVoltage.length;i++)expect(Math.abs(dc.nodeVoltage[i]),name+': V too large').toBeLessThan(maxRail+10);});}});
