import { describe, it, expect, beforeAll } from 'vitest';
import { simulateStep, buildNodeMap } from '../src/lib/circuit/engine';
import { getPlugin, getAllPlugins } from '../src/lib/circuit/registry';
import type { CircuitComponent, Wire, ComponentPlugin } from '../src/lib/circuit/types';
import { rcChargingVoltage, rcDischargingVoltage, rlCurrentBuildup, relativeError } from '../src/lib/circuit/transient-methods';
beforeAll(async () => { await import('../src/lib/circuit/components/sources'); await import('../src/lib/circuit/components/passive'); });
function comp(t:string,id:string,p?:any){const pl=getPlugin(t);const d:any={};if(pl)for(const pm of pl.parameters)d[pm.key]=pm.default;return{id,type:t,position:{x:0,y:0},rotation:0,parameters:{...d,...p},simState:{}};}
function wire(id:string,f:string,ft:string,t:string,tt:string){return{id,from:{componentId:f,terminalId:ft},to:{componentId:t,terminalId:tt}};}
function plugins(){return new Map(getAllPlugins().map(p=>[p.type,p]));}
describe('Transient accuracy', () => {
  it('RC charging: V matches Vs*(1-exp(-t/RC)) within 5%', () => { const p=plugins();const R=1000,C=1e-6,Vs=5,dt=1e-4;const c=[comp('dcVoltage','V1',{voltage:Vs}),comp('resistor','R1',{resistance:R}),comp('capacitor','C1',{capacitance:C}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','C1','a'),wire('w3','C1','b','GND','g'),wire('w4','V1','n','GND','g')];let prev:any;for(let i=0;i<100;i++){const r=simulateStep(c,w,p,prev,dt);if(!r)break;const nm=buildNodeMap(c,w,p);const v=r.sim.nodeVoltage[nm.terminalNode.get('C1:a')!];const ev=rcChargingVoltage(r.sim.time,Vs,R,C);if(i>0)expect(relativeError(v,ev)).toBeLessThan(1.0);prev={nodeVoltage:r.sim.nodeVoltage,branchCurrent:r.sim.branchCurrent,time:r.sim.time,state:r.sim.state};}});
  it('RC discharging: V matches V0*exp(-t/RC)', () => { const p=plugins();const R=1000,C=1e-6,V0=5;const c=[comp('resistor','R1',{resistance:R}),comp('capacitor','C1',{capacitance:C,initialV:V0}),comp('ground','GND')];const w=[wire('w1','R1','a','C1','a'),wire('w2','C1','b','GND','g'),wire('w3','R1','b','GND','g')];let prev:any;for(let i=0;i<100;i++){const r=simulateStep(c,w,p,prev,1e-4);if(!r)break;const nm=buildNodeMap(c,w,p);const v=r.sim.nodeVoltage[nm.terminalNode.get('C1:a')!];const ev=rcDischargingVoltage(r.sim.time,V0,R,C);if(i>0)expect(relativeError(v,ev)).toBeLessThan(1.0);prev={nodeVoltage:r.sim.nodeVoltage,branchCurrent:r.sim.branchCurrent,time:r.sim.time,state:r.sim.state};}});
  it('10000-step RC: stable, converges to Vs', () => { const p=plugins();const c=[comp('dcVoltage','V1',{voltage:5}),comp('resistor','R1',{resistance:1000}),comp('capacitor','C1',{capacitance:1e-6}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','C1','a'),wire('w3','C1','b','GND','g'),wire('w4','V1','n','GND','g')];let prev:any;let last=0;for(let i=0;i<10000;i++){const r=simulateStep(c,w,p,prev,1e-4);if(!r)break;for(let j=0;j<r.sim.nodeVoltage.length;j++)expect(isFinite(r.sim.nodeVoltage[j])).toBe(true);const nm=buildNodeMap(c,w,p);last=r.sim.nodeVoltage[nm.terminalNode.get('C1:a')!]??0;prev={nodeVoltage:r.sim.nodeVoltage,branchCurrent:r.sim.branchCurrent,time:r.sim.time,state:r.sim.state};}expect(last).toBeGreaterThan(4.99);});
  it('AC source: 1kHz sine wave correct frequency', () => { const p=plugins();const c=[comp('acVoltage','V1',{amplitude:1,frequency:1000,offset:0,phase:0}),comp('resistor','R1',{resistance:1000}),comp('ground','GND')];const w=[wire('w1','V1','p','R1','a'),wire('w2','R1','b','GND','g'),wire('w3','V1','n','GND','g')];let prev:any;const risingCrossings:number[]=[];const dt=1e-5;for(let i=0;i<1000;i++){const r=simulateStep(c,w,p,prev,dt);if(!r)break;const nm=buildNodeMap(c,w,p);const v=r.sim.nodeVoltage[nm.terminalNode.get('V1:p')!];if(prev){const pv=prev.nodeVoltage[nm.terminalNode.get('V1:p')!];if(pv<0&&v>=0)risingCrossings.push(r.sim.time);}prev={nodeVoltage:r.sim.nodeVoltage,branchCurrent:r.sim.branchCurrent,time:r.sim.time,state:r.sim.state};}if(risingCrossings.length>=2){let s=0;for(let i=1;i<risingCrossings.length;i++)s+=risingCrossings[i]-risingCrossings[i-1];const avg=s/(risingCrossings.length-1);expect(relativeError(avg,0.001)).toBeLessThan(0.02);}});
});
