// Electronics Knowledge Base — structured articles for AI-assisted learning.
//
// Each article has: id, title, category, tags, summary, body (markdown),
// related concepts, and "see also" links. The KB is searchable by tag,
// category, or free-text match on title+summary+body.
//
// Articles are written for a learner audience — assume the reader knows basic
// algebra but may not know what a "transimpedance" is. Each article aims to
// answer: "What is this?", "How does it work?", "How do I use it?", and
// "What goes wrong?".
//
// The AI can retrieve articles via the 'kb.lookup' tool and cite them in
// responses. The KnowledgeBase browser UI (in HelpDialog) lets users browse
// the full library without involving the AI.
//
// NOTE: Article bodies use markdown with single-quote code spans (e.g. 'V = IR')
// instead of backtick code spans, to avoid template-literal escaping issues.

export interface KBTag {
  tag: string;
  label: string;
}

export interface KBArticle {
  id: string;
  title: string;
  category: 'passives' | 'semiconductors' | 'ic' | 'concepts' | 'analysis' | 'troubleshooting' | 'pcb' | 'design-patterns';
  tags: string[];
  summary: string;
  body: string;
  related?: string[];
  seeAlso?: string[];
}

export const KB_CATEGORIES: { id: KBArticle['category']; label: string; icon: string }[] = [
  { id: 'concepts', label: 'Core Concepts', icon: '📚' },
  { id: 'passives', label: 'Passive Components', icon: '🔲' },
  { id: 'semiconductors', label: 'Semiconductors', icon: '🔺' },
  { id: 'ic', label: 'Integrated Circuits', icon: '🔧' },
  { id: 'analysis', label: 'Analysis Techniques', icon: '📊' },
  { id: 'troubleshooting', label: 'Troubleshooting', icon: '🔍' },
  { id: 'design-patterns', label: 'Design Patterns', icon: '🧩' },
  { id: 'pcb', label: 'PCB Layout', icon: '🖥️' },
];

// Helper to build article bodies without backtick conflicts.
// Uses array join for readability.
function body(lines: string[]): string {
  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// CORE CONCEPTS
// ─────────────────────────────────────────────────────────────────────────────

const ohmsLaw: KBArticle = {
  id: 'ohms-law',
  title: "Ohm's Law",
  category: 'concepts',
  tags: ['voltage', 'current', 'resistance', 'fundamental', 'dc'],
  summary: 'The fundamental relationship between voltage (V), current (I), and resistance (R): V = I·R. Every circuit analysis starts here.',
  body: body([
    "# Ohm's Law",
    "",
    "**V = I · R**",
    "",
    "Where:",
    "- **V** = voltage across the resistor (volts, V)",
    "- **I** = current through the resistor (amperes, A)",
    "- **R** = resistance (ohms, Ω)",
    "",
    "## The Three Forms",
    "",
    "| You know... | Solve for | Formula |",
    "|---|---|---|",
    "| V and R | I | I = V / R |",
    "| V and I | R | R = V / I |",
    "| I and R | V | V = I · R |",
    "",
    "## Intuition",
    "",
    "Think of water flowing through a pipe:",
    "- **Voltage** = water pressure",
    "- **Current** = flow rate",
    "- **Resistance** = pipe narrowness",
    "",
    "Higher pressure → more flow. Narrower pipe → less flow. This is Ohm's Law.",
    "",
    "## Worked Example",
    "",
    "A 330 Ω resistor is connected across a 5 V supply. What's the current?",
    "",
    "I = V / R = 5 / 330 = 0.0152 A = **15.2 mA**",
    "",
    "This is the classic LED current-limiting calculation.",
    "",
    "## Power Dissipation",
    "",
    "A resistor converts electrical energy to heat. The power is:",
    "",
    "**P = V · I = I² · R = V² / R**",
    "",
    "For the 330 Ω / 5 V example: P = 5² / 330 = 0.076 W = 76 mW. A standard ¼W resistor handles this easily.",
    "",
    "## Common Mistakes",
    "",
    "1. **Forgetting units** — mixing mA with Ω gives wrong volts. Always convert to base units (A, Ω, V).",
    "2. **Using supply voltage instead of resistor voltage** — if two resistors form a divider, each resistor sees only its share of the supply.",
    "3. **Ignoring power rating** — a 10 Ω resistor across 12 V dissipates 14.4 W. A ¼W resistor will smoke.",
    "",
    "## When Ohm's Law Doesn't Apply",
    "",
    "- **Diodes and LEDs** — non-ohmic (current is exponential, not linear)",
    "- **Transistors** — controlled current sources, not resistors",
    "- **Capacitors and inductors** — voltage/current relationship involves time, not just instant values",
    "- **Superconductors** — R = 0, so V = 0 regardless of I",
  ]),
  related: ['kvl-kcl', 'voltage-divider', 'kvl-kcl'],
  seeAlso: ['led-current-limiting'],
};

const kvlKcl: KBArticle = {
  id: 'kvl-kcl',
  title: "Kirchhoff's Voltage and Current Laws (KVL / KCL)",
  category: 'concepts',
  tags: ['kvl', 'kcl', 'fundamental', 'circuit-analysis', 'nodes', 'loops'],
  summary: 'KVL: sum of voltages around any loop = 0. KCL: sum of currents at any node = 0. These two laws, plus Ohm\'s Law, solve every linear circuit.',
  body: body([
    "# Kirchhoff's Laws",
    "",
    "## Kirchhoff's Voltage Law (KVL)",
    "",
    "**The sum of all voltages around any closed loop is zero.**",
    "",
    "Σ V = 0 (around a loop)",
    "",
    "This is conservation of energy: the energy gained from sources equals the energy lost in loads.",
    "",
    "### Example",
    "",
    "A 12 V battery powers two resistors in series (R1 = 4 Ω, R2 = 2 Ω).",
    "",
    "Starting at the battery's negative terminal and walking clockwise:",
    "- +12 V (battery, - to +)",
    "- −8 V (R1, voltage drop: I·R1 = 2·4 = 8)",
    "- −4 V (R2, voltage drop: I·R2 = 2·2 = 4)",
    "",
    "Sum: 12 − 8 − 4 = 0 ✓",
    "",
    "## Kirchhoff's Current Law (KCL)",
    "",
    "**The sum of all currents entering a node equals the sum leaving.**",
    "",
    "Σ I_in = Σ I_out",
    "",
    "This is conservation of charge: charge can't accumulate at a node.",
    "",
    "### Example",
    "",
    "Three resistors meet at a node. 2 A flows in through R1, 0.5 A flows out through R2. What's the current through R3?",
    "",
    "2 = 0.5 + I_R3 → I_R3 = 1.5 A (leaving the node)",
    "",
    "## How to Use Them",
    "",
    "1. **Label** every node (A, B, C, ...) and every current direction (arbitrary — if you guess wrong, the answer is negative).",
    "2. **Apply KCL** at each unknown node → gives one equation per node.",
    "3. **Apply KVL** around each independent loop → gives one equation per loop.",
    "4. **Solve** the system of linear equations (matrix method or substitution).",
    "",
    "For N nodes, you get N−1 independent KCL equations. For M meshes (independent loops), you get M KVL equations.",
    "",
    "## Nodal Analysis (the practical method)",
    "",
    "Most circuit simulators (including this one) use **nodal analysis**:",
    "1. Pick a reference node (ground, V = 0).",
    "2. For every other node, write KCL with currents expressed via Ohm's Law.",
    "3. Solve the resulting linear system Ax = b, where x is the vector of node voltages.",
    "",
    "This is exactly what the MNA (Modified Nodal Analysis) solver in this simulator does.",
    "",
    "## Common Mistakes",
    "",
    "1. **Sign errors in KVL** — voltage rises (sources) are positive, drops (loads) are negative. Walk the loop in one direction and be consistent.",
    "2. **Counting nodes wrong** — two points connected by a wire are the SAME node. A node is a region of equipotential.",
    "3. **Forgetting ground** — every circuit needs a reference (ground = 0 V). Without it, voltages are undefined and the simulator returns 'singular matrix'.",
  ]),
  related: ['ohms-law', 'voltage-divider'],
  seeAlso: ['floating-node', 'missing-ground'],
};

const voltageDivider: KBArticle = {
  id: 'voltage-divider',
  title: 'Voltage Divider',
  category: 'concepts',
  tags: ['voltage-divider', 'resistor', 'dc', 'fundamental'],
  summary: 'Two series resistors split a voltage: V_out = V_in · R2/(R1+R2). The most common circuit pattern in electronics.',
  body: body([
    "# Voltage Divider",
    "",
    "## The Circuit",
    "",
    "  V_in ──[R1]──┬──[R2]── GND",
    "               │",
    "             V_out",
    "",
    "## The Formula",
    "",
    "**V_out = V_in · R2 / (R1 + R2)**",
    "",
    "## Derivation (using Ohm's Law + KVL)",
    "",
    "1. The current through both resistors: I = V_in / (R1 + R2)",
    "2. The voltage across R2: V_out = I · R2 = V_in · R2 / (R1 + R2)",
    "",
    "## Worked Example",
    "",
    "R1 = 10 kΩ, R2 = 10 kΩ, V_in = 5 V.",
    "",
    "V_out = 5 · 10000 / 20000 = 2.5 V",
    "",
    "A 50/50 divider halves the input. Obvious but useful.",
    "",
    "## The Loading Problem",
    "",
    "**The formula only works if nothing draws current from V_out.**",
    "",
    "If you connect a load R_load to V_out, the lower leg becomes R2 ∥ R_load, and the output drops.",
    "",
    "### Example",
    "",
    "R1 = R2 = 10 kΩ, V_in = 5 V. You connect a 10 kΩ load.",
    "",
    "Effective lower leg = 10k ∥ 10k = 5 kΩ.",
    "",
    "V_out = 5 · 5000 / (10000 + 5000) = 1.67 V (not 2.5 V!)",
    "",
    "**Rule of thumb:** for the divider to be 'stiff', R1 + R2 should be at least 10× smaller than R_load.",
    "",
    "## When to Use a Divider vs. a Regulator",
    "",
    "| Need | Use |",
    "|---|---|",
    "| Fixed reference for a high-impedance input (ADC, op-amp) | Divider is fine |",
    "| Powering a load that draws current | Use a voltage regulator (LM7805, etc.) |",
    "| Variable voltage (potentiometer) | Divider with a pot — but buffer with an op-amp if loaded |",
    "",
    "## Common Mistakes",
    "",
    "1. **Loading the divider** — connecting a low-impedance load drops the voltage.",
    "2. **Using too-high values** — 1 MΩ + 1 MΩ draws little current but is noisy and susceptible to interference.",
    "3. **Using too-low values** — 100 Ω + 100 Ω across 5 V wastes 25 mA and dissipates 125 mW.",
    "4. **Expecting precision** — 5% resistors give a 5% output tolerance. Use 1% or better for references.",
  ]),
  related: ['ohms-law', 'kvl-kcl'],
  seeAlso: ['led-current-limiting'],
};

const capacitorBasics: KBArticle = {
  id: 'capacitor-basics',
  title: 'Capacitors: Energy Storage and AC Behavior',
  category: 'passives',
  tags: ['capacitor', 'reactance', 'frequency', 'ac', 'transient', 'decoupling'],
  summary: 'A capacitor stores charge. In DC, it blocks steady current after charging. In AC, its impedance is 1/(jωC) — it passes high frequencies and blocks low ones.',
  body: body([
    "# Capacitors",
    "",
    "## What It Is",
    "",
    "A capacitor stores electrical energy in an electric field between two conductive plates separated by an insulator (dielectric).",
    "",
    "**Q = C · V**",
    "",
    "Where:",
    "- Q = stored charge (coulombs, C)",
    "- C = capacitance (farads, F)",
    "- V = voltage across the capacitor (volts, V)",
    "",
    "## Current-Voltage Relationship",
    "",
    "**I = C · dV/dt**",
    "",
    "The current through a capacitor is proportional to how fast the voltage is changing.",
    "",
    "## DC Behavior (Transient)",
    "",
    "When you connect a capacitor to a DC source through a resistor:",
    "",
    "1. **t = 0**: Capacitor is uncharged (V = 0). It acts as a short circuit. Current = V/R.",
    "2. **Charging**: V(t) = V_final · (1 − e^(−t/RC))",
    "3. **t = ∞**: Capacitor is fully charged. It acts as an open circuit. Current = 0.",
    "",
    "### Time Constant",
    "",
    "**τ = R · C** (seconds)",
    "",
    "At t = τ, the capacitor charges to 63.2% of final. At t = 5τ, it's considered fully charged (99.3%).",
    "",
    "### Example",
    "",
    "R = 10 kΩ, C = 1 µF → τ = 10 ms. The capacitor charges in ~50 ms.",
    "",
    "## AC Behavior (Steady State)",
    "",
    "In AC, the capacitor's impedance is:",
    "",
    "**Z_C = 1 / (jωC) = −j / (2πfC)**",
    "",
    "- At **low frequency**: |Z| is large → blocks signal",
    "- At **high frequency**: |Z| is small → passes signal",
    "",
    "This is why capacitors are used as **high-pass filters** (in series) and **low-pass filters** (in parallel / shunt).",
    "",
    "## Capacitor Types",
    "",
    "| Type | Typical Use | Notes |",
    "|---|---|---|",
    "| Ceramic (X7R, C0G) | Decoupling, high-freq filters | Cheap, small, low ESR |",
    "| Electrolytic | Bulk power supply filtering | High C, polarized, higher ESR |",
    "| Tantalum | Compact bulk, low ESR | Polarized, can fail spectacularly |",
    "| Film | Audio, precision timing | Excellent stability, larger |",
    "| Supercapacitor | Energy storage, backup | Thousands of farads, low voltage |",
    "",
    "## Common Applications",
    "",
    "### 1. Decoupling (Bypass) Capacitor",
    "Placed next to an IC's power pin to supply transient current and filter noise. Typically 100 nF ceramic + 10 µF electrolytic.",
    "",
    "### 2. RC Low-Pass Filter",
    "  Signal ──[R]──┬── Output",
    "                [C]",
    "                GND",
    "",
    "Cutoff frequency: f_c = 1 / (2πRC)",
    "",
    "### 3. RC High-Pass Filter",
    "  Signal ──[C]──┬── Output",
    "                [R]",
    "                GND",
    "",
    "Same cutoff formula.",
    "",
    "### 4. Timing",
    "An RC network charges/discharges predictably — used in 555 timers, debounce circuits, reset generators.",
    "",
    "## Common Mistakes",
    "",
    "1. **Forgetting polarity** (electrolytics) — reversed polarity = explosion.",
    "2. **Wrong voltage rating** — a 6.3 V cap on a 12 V rail = failure.",
    "3. **Using electrolytic for high-freq decoupling** — ESR too high. Always pair with a 100 nF ceramic.",
    "4. **Ignoring DC bias effect** — some ceramic caps (Class II, X7R) lose 50%+ capacitance at rated voltage.",
    "5. **Not calculating ripple current** — in power supplies, the cap's ESR × ripple current = heat.",
  ]),
  related: ['inductor-basics', 'decoupling'],
  seeAlso: ['555-timer'],
};

const inductorBasics: KBArticle = {
  id: 'inductor-basics',
  title: 'Inductors: Energy Storage and AC Behavior',
  category: 'passives',
  tags: ['inductor', 'reactance', 'frequency', 'ac', 'transient', 'magnetic'],
  summary: 'An inductor stores energy in a magnetic field. In DC, it acts as a short after transients. In AC, its impedance is jωL — it blocks high frequencies and passes low ones.',
  body: body([
    "# Inductors",
    "",
    "## What It Is",
    "",
    "An inductor stores energy in a magnetic field created by current flowing through a coil.",
    "",
    "**V = L · dI/dt**",
    "",
    "The voltage across an inductor is proportional to how fast the current is changing.",
    "",
    "## DC Behavior (Transient)",
    "",
    "When you connect an inductor to a DC source through a resistor:",
    "",
    "1. **t = 0**: Inductor opposes current change. It acts as an open circuit. Current = 0.",
    "2. **Charging**: I(t) = I_final · (1 − e^(−t·R/L))",
    "3. **t = ∞**: Inductor is fully energized. It acts as a short circuit (wire). Current = V/R.",
    "",
    "### Time Constant",
    "",
    "**τ = L / R** (seconds)",
    "",
    "## AC Behavior (Steady State)",
    "",
    "**Z_L = jωL = j · 2πfL**",
    "",
    "- At **low frequency**: |Z| is small → passes signal",
    "- At **high frequency**: |Z| is large → blocks signal",
    "",
    "Opposite of a capacitor!",
    "",
    "## Inductor Types",
    "",
    "| Type | Typical Use | Notes |",
    "|---|---|---|",
    "| Air core | High-freq RF | No saturation, low L |",
    "| Iron core | Audio, power | High L, saturates |",
    "| Ferrite | SMPS, EMI filters | Good up to ~100 MHz |",
    "| Toroid | RF, filters | Self-shielding, low radiation |",
    "",
    "## Common Applications",
    "",
    "### 1. DC-DC Converters (Buck, Boost)",
    "The inductor stores energy during the switch-on phase and releases it during switch-off. The fundamental component of every switching regulator.",
    "",
    "### 2. LC Filter",
    "  Signal ──[L]──┬── Output",
    "                [C]",
    "                GND",
    "",
    "Second-order low-pass. Cutoff: f_c = 1 / (2π√(LC))",
    "",
    "### 3. EMI / Noise Filter",
    "A ferrite bead on a power line blocks high-frequency noise while passing DC.",
    "",
    "### 4. RF Tuned Circuit",
    "LC tank resonates at f = 1 / (2π√(LC)). Used in oscillators, radios.",
    "",
    "## Common Mistakes",
    "",
    "1. **No flyback diode** — when an inductor's current is interrupted (e.g. relay turns off), V = L·dI/dt spikes to hundreds of volts. Always put a diode across the inductor (cathode to V+) to clamp the spike.",
    "2. **Saturation** — a ferrite core saturates above a certain current, causing L to drop dramatically. Check the saturation current rating.",
    "3. **DC resistance** — real inductors have series resistance (DCR). In power applications, this causes I²R losses and heating.",
    "4. **Self-resonance** — the inductor's parasitic capacitance creates a self-resonant frequency (SRF). Above SRF, it behaves as a capacitor.",
  ]),
  related: ['capacitor-basics', 'flyback-diode'],
  seeAlso: [],
};

// ─────────────────────────────────────────────────────────────────────────────
// SEMICONDUCTORS
// ─────────────────────────────────────────────────────────────────────────────

const diodeBasics: KBArticle = {
  id: 'diode-basics',
  title: 'Diodes: One-Way Valves',
  category: 'semiconductors',
  tags: ['diode', 'pn-junction', 'rectification', 'forward-bias', 'reverse-bias'],
  summary: 'A diode conducts current in one direction (forward bias, V > ~0.7 V for silicon) and blocks it in the other. The foundation of all semiconductors.',
  body: body([
    "# Diodes",
    "",
    "## The I-V Curve",
    "",
    "  Current",
    "    │       ↗ exponential (forward bias)",
    "    │      /",
    "    │     /",
    "    │    / V_f ≈ 0.7 V (silicon)",
    "  ──┼───/────────── Voltage",
    "      \\─── breakdown (reverse)",
    "        \\",
    "",
    "## Forward Bias (Anode > Cathode)",
    "",
    "When V_AK > V_f (forward voltage, ~0.7 V for Si, ~0.3 V for Schottky, ~2-3 V for LEDs):",
    "",
    "- The diode conducts with very low resistance.",
    "- V_AK stays clamped near V_f regardless of current (within a reasonable range).",
    "",
    "## Reverse Bias (Cathode > Anode)",
    "",
    "- Only a tiny leakage current flows (nA to µA).",
    "- The diode acts as an open circuit.",
    "",
    "## Reverse Breakdown",
    "",
    "If the reverse voltage exceeds the breakdown voltage (V_BR), the diode conducts heavily. For a regular diode this destroys it. For a **Zener diode**, this is the intended operating region — it clamps the voltage at V_Z.",
    "",
    "## Key Parameters",
    "",
    "| Parameter | Typical (1N4148) | Meaning |",
    "|---|---|---|",
    "| V_f | 0.7 V | Forward voltage drop |",
    "| I_F(max) | 200 mA | Max continuous forward current |",
    "| V_R(max) | 100 V | Max reverse voltage before breakdown |",
    "| t_rr | 4 ns | Reverse recovery time (how fast it turns off) |",
    "",
    "## Common Diode Types",
    "",
    "| Type | V_f | Use |",
    "|---|---|---|",
    "| Rectifier (1N4007) | 0.7 V | AC→DC rectification, slow |",
    "| Signal (1N4148) | 0.7 V | General purpose, fast |",
    "| Schottky (1N5817) | 0.3 V | Low-drop rectification, fast |",
    "| Zener (1N4733) | varies | Voltage reference (reverse mode) |",
    "| LED | 1.8-3.5 V | Light emitter |",
    "| TVS | varies | Transient voltage suppressor |",
    "",
    "## Applications",
    "",
    "### 1. Half-Wave Rectifier",
    "  AC ──[D]──┬── DC (pulsing)",
    "            [C]  (filter cap smooths it)",
    "            GND",
    "",
    "### 2. Reverse Polarity Protection",
    "Put a diode in series with the power input. If the user connects the battery backwards, the diode blocks current.",
    "",
    "### 3. Flyback (Freewheeling) Diode",
    "Across an inductor (relay, motor) to clamp the voltage spike when the inductor current is interrupted. Cathode to V+.",
    "",
    "### 4. Logic OR",
    "Two diodes, anodes from two inputs, cathodes tied to output through a resistor. Either input high → output high.",
    "",
    "## Common Mistakes",
    "",
    "1. **Wrong polarity** — the stripe on the package is the cathode. Reversing it in a rectifier circuit = short.",
    "2. **Exceeding I_F(max)** — diode smokes. Check the datasheet.",
    "3. **Forgetting V_f in calculations** — a '5 V' supply through a silicon diode gives 4.3 V.",
    "4. **Using a slow diode in a SMPS** — 1N4007 has t_rr = 30 µs. A 100 kHz SMPS needs t_rr < 100 ns. Use a Schottky or fast-recovery diode.",
  ]),
  related: ['led-current-limiting', 'flyback-diode'],
  seeAlso: ['transistor-basics'],
};

const ledCurrentLimiting: KBArticle = {
  id: 'led-current-limiting',
  title: 'LED Current Limiting Resistor',
  category: 'semiconductors',
  tags: ['led', 'resistor', 'current-limiting', 'design-pattern', 'beginner'],
  summary: 'An LED needs a series resistor to set the current: R = (V_supply − V_LED) / I_LED. Without it, the LED draws unlimited current and burns out.',
  body: body([
    "# LED Current Limiting",
    "",
    "## Why You Need a Resistor",
    "",
    "An LED is a diode. Once V_LED exceeds the forward voltage (1.8-3.5 V depending on color), the current increases exponentially. A tiny voltage change causes a huge current change.",
    "",
    "Without a resistor:",
    "- 5 V across a 2 V red LED → I is limited only by the supply's internal resistance → LED dies.",
    "",
    "## The Formula",
    "",
    "**R = (V_supply − V_LED) / I_LED**",
    "",
    "Where:",
    "- V_supply = supply voltage (V)",
    "- V_LED = LED forward voltage (V) — check the LED datasheet",
    "- I_LED = desired LED current (A) — typically 10-20 mA for indicator LEDs",
    "",
    "## Typical V_LED by Color",
    "",
    "| Color | V_LED (typical) |",
    "|---|---|",
    "| Red | 1.8 V |",
    "| Yellow | 2.0 V |",
    "| Green | 2.1 V |",
    "| Blue | 3.0 V |",
    "| White | 3.2 V |",
    "| IR | 1.2 V |",
    "",
    "## Worked Example",
    "",
    "5 V supply, red LED (V_LED = 1.8 V), target 15 mA.",
    "",
    "R = (5 − 1.8) / 0.015 = 3.2 / 0.015 = 213 Ω",
    "",
    "Nearest standard value: 220 Ω. Recalculate actual current:",
    "",
    "I = (5 − 1.8) / 220 = 14.5 mA — close enough.",
    "",
    "## Power Dissipation in the Resistor",
    "",
    "P = I² · R = (0.0145)² · 220 = 46 mW",
    "",
    "A ¼W (250 mW) resistor is fine. A ⅛W (125 mW) is also fine.",
    "",
    "## Multiple LEDs",
    "",
    "### Parallel (each with its own resistor)",
    "  V ──[R1]──[LED1]── GND",
    "    ──[R2]──[LED2]── GND",
    "",
    "Each LED needs its own resistor because V_LED varies between LEDs (even of the same color). Without individual resistors, one LED hogs current and dies.",
    "",
    "### Series (one resistor for all)",
    "  V ──[R]──[LED1]──[LED2]──[LED3]── GND",
    "",
    "R = (V_supply − n·V_LED) / I_LED where n = number of LEDs.",
    "",
    "Requires V_supply > n · V_LED. More efficient (one resistor, same current through all LEDs).",
    "",
    "## Common Mistakes",
    "",
    "1. **No resistor** — LED burns out in seconds.",
    "2. **Wrong resistor value** — too low = bright then dead; too high = dim.",
    "3. **Parallel LEDs with one resistor** — current sharing is terrible, one LED dies.",
    "4. **Forgetting V_LED varies** — blue LEDs need higher V_supply or fewer in series.",
    "5. **Using PWM without a resistor** — even at 50% duty, the peak current is unlimited.",
  ]),
  related: ['ohms-law', 'diode-basics'],
  seeAlso: ['voltage-divider', 'transistor-switch'],
};

const transistorBasics: KBArticle = {
  id: 'transistor-basics',
  title: 'BJT Transistors: Current Amplifiers',
  category: 'semiconductors',
  tags: ['transistor', 'bjt', 'npn', 'pnp', 'amplifier', 'switch', 'current'],
  summary: 'A BJT is a current-controlled current source: a small base current controls a larger collector current (I_C = h_FE · I_B). Used as switches and amplifiers.',
  body: body([
    "# BJT Transistors",
    "",
    "## The Three Terminals",
    "",
    "- **Base (B)** — the control input (small current)",
    "- **Collector (C)** — the main current input (large current)",
    "- **Emitter (E)** — the common terminal (current flows out for NPN)",
    "",
    "## NPN vs PNP",
    "",
    "| | NPN | PNP |",
    "|---|---|---|",
    "| Arrow direction | Points OUT (emitter) | Points IN (emitter) |",
    "| Conducts when | V_B > V_E (+0.7 V) | V_B < V_E (−0.7 V) |",
    "| Current flow | C → E (conventional) | E → C |",
    "",
    "## The Three Operating Regions",
    "",
    "### 1. Cutoff (Switch OFF)",
    "- V_BE < 0.7 V",
    "- I_B = 0, I_C = 0",
    "- Transistor is OFF",
    "",
    "### 2. Active (Amplifier)",
    "- V_BE ≈ 0.7 V",
    "- I_C = h_FE · I_B (linear relationship)",
    "- V_CE > V_CE(sat) ≈ 0.2 V",
    "- Used in analog amplifiers",
    "",
    "### 3. Saturation (Switch ON)",
    "- V_BE ≈ 0.7 V, V_CE ≈ 0.2 V",
    "- I_C is limited by the external circuit, not by h_FE · I_B",
    "- Transistor is fully ON",
    "",
    "## The h_FE (Beta) Parameter",
    "",
    "h_FE (also called β) is the DC current gain. It varies wildly:",
    "- Typical: 100",
    "- Range: 50 to 400 (even for the same part number!)",
    "- Temperature dependent",
    "",
    "**Never design a circuit that depends on a specific h_FE value.** Always design for the minimum h_FE in the datasheet.",
    "",
    "## Worked Example: Transistor as a Switch",
    "",
    "Drive an LED with 20 mA from a 3.3 V microcontroller pin (which can only source 5 mA).",
    "",
    "  3.3 V ──[R_base]── Base",
    "                  │",
    "              NPN Transistor",
    "                  │",
    "  5 V ──[R_led]── Collector",
    "                  │",
    "                LED",
    "                  │",
    "                 GND ── Emitter",
    "",
    "### Step 1: LED Resistor",
    "R_led = (5 − 2.0 − 0.2) / 0.020 = 140 Ω → use 150 Ω",
    "",
    "### Step 2: Base Resistor",
    "I_C = 20 mA. Assuming h_FE(min) = 100, we need I_B = I_C / h_FE = 0.2 mA.",
    "",
    "For saturation, use 2-5× this: I_B = 1 mA.",
    "",
    "R_base = (3.3 − 0.7) / 0.001 = 2.6 kΩ → use 2.2 kΩ",
    "",
    "## Common-Emitter Amplifier",
    "",
    "  V_cc",
    "   │",
    "  [R_c] ← collector resistor",
    "   │",
    "   C ──── Output",
    "   │",
    "  [Q1] (NPN)",
    "   │",
    "   E ──[R_e]── GND  ← emitter resistor (for stability)",
    "   │",
    "   B ── Input (through coupling cap)",
    "",
    "The emitter resistor provides negative feedback: if I_C increases, V_E increases, which reduces V_BE, which reduces I_C. This stabilizes the operating point against h_FE variation.",
    "",
    "## Common Mistakes",
    "",
    "1. **No base resistor** — base is a diode to emitter. Without a resistor, I_B is unlimited → transistor dies.",
    "2. **Forgetting V_BE(sat) = 0.7 V** — the base needs 0.7 V above the emitter.",
    "3. **Not saturating in switch mode** — if I_B is too low, the transistor stays in active region, V_CE is high, and it dissipates P = V_CE · I_C → overheats.",
    "4. **Exceeding I_C(max)** — check the datasheet. A 2N3904 handles 200 mA; a TIP120 handles 5 A.",
    "5. **No flyback diode for inductive loads** — relay/motor coils generate voltage spikes when switched off. Always add a diode across the load.",
  ]),
  related: ['mosfet-basics', 'transistor-switch'],
  seeAlso: ['led-current-limiting', 'flyback-diode'],
};

const mosfetBasics: KBArticle = {
  id: 'mosfet-basics',
  title: 'MOSFETs: Voltage-Controlled Switches',
  category: 'semiconductors',
  tags: ['mosfet', 'nmos', 'pmos', 'switch', 'voltage-controlled', 'power'],
  summary: 'A MOSFET is a voltage-controlled device: V_GS > V_th turns it ON. Unlike BJTs, the gate draws no DC current. Ideal for switching and high-power loads.',
  body: body([
    "# MOSFETs",
    "",
    "## The Three Terminals",
    "",
    "- **Gate (G)** — the control input (voltage, no current)",
    "- **Drain (D)** — the main current input",
    "- **Source (S)** — the common terminal",
    "",
    "## NMOS vs PMOS",
    "",
    "| | NMOS | PMOS |",
    "|---|---|---|",
    "| Conducts when | V_GS > V_th (positive) | V_GS < −V_th (negative) |",
    "| Typical use | Low-side switch (load to V+) | High-side switch (load to GND) |",
    "| Body diode | S→D (cathode at D) | D→S (cathode at S) |",
    "",
    "## Operating Regions",
    "",
    "### 1. Cutoff (OFF)",
    "- V_GS < V_th",
    "- I_D = 0",
    "",
    "### 2. Saturation (Active / Amplifier)",
    "- V_GS > V_th AND V_DS > V_GS − V_th",
    "- I_D = ½ · k · (V_GS − V_th)² (square law)",
    "- Used in analog amplifiers",
    "",
    "### 3. Linear / Triode (Switch ON)",
    "- V_GS > V_th AND V_DS < V_GS − V_th",
    "- R_DS(on) is low (mΩ for power MOSFETs)",
    "- Used as a switch",
    "",
    "## V_th (Threshold Voltage)",
    "",
    "- Logic-level MOSFET: V_th = 1-2 V (fully ON at V_GS = 5 V)",
    "- Standard MOSFET: V_th = 2-4 V (needs V_GS = 10 V to fully turn on)",
    "",
    "**For microcontroller projects, always use logic-level MOSFETs.**",
    "",
    "## Worked Example: Switching a 12 V LED Strip (1 A)",
    "",
    "  12 V ──[LED strip]── Drain",
    "                      │",
    "                  NMOS (IRLZ44N, logic-level)",
    "                      │",
    "                     GND ── Source",
    "                      │",
    "  3.3 V MCU ──[R_gate]── Gate",
    "                      │",
    "                    [R_pulldown] (10k to GND)",
    "",
    "### Why a Gate Pulldown?",
    "A MOSFET gate is essentially a capacitor. When the MCU pin is floating (during reset), the gate holds its charge unpredictably. A 10 kΩ pulldown ensures the MOSFET is OFF when the MCU is not actively driving it.",
    "",
    "### Why a Gate Resistor?",
    "The gate is a capacitor (C_iss, typically 1-10 nF). When the MCU pin transitions, a large instantaneous current flows. A 100-220 Ω resistor limits this and protects the MCU.",
    "",
    "## R_DS(on) — The Key Parameter",
    "",
    "In the ON state, a MOSFET acts as a resistor R_DS(on).",
    "",
    "- Power MOSFET: R_DS(on) = 10-50 mΩ",
    "- At 5 A, P = I²·R = 25 · 0.05 = 1.25 W — needs a heatsink",
    "- At 5 A with R_DS(on) = 5 mΩ: P = I²·R = 25 · 0.005 = 0.125 W — much better",
    "",
    "## Body Diode",
    "",
    "Every MOSFET has a built-in body diode (parasitic). For NMOS, it points from source to drain.",
    "",
    "- This is why MOSFETs are used as flyback diodes in synchronous buck converters",
    "- For relay/motor flyback, an external Schottky is often better (faster)",
    "",
    "## Common Mistakes",
    "",
    "1. **Using a non-logic level MOSFET with a 3.3 V MCU** — V_GS = 3.3 V < V_th = 4 V → MOSFET never turns on.",
    "2. **No gate pulldown** — MOSFET turns on randomly during MCU reset.",
    "3. **No gate resistor** — large current spikes can damage the MCU.",
    "4. **Exceeding V_GS(max)** — typically ±20 V. A 24 V gate drive needs a zener clamp.",
    "5. **Forgetting the body diode** — if you reverse V_DS, the body diode conducts regardless of gate.",
    "6. **Not heatsinking** — even R_DS(on) = 10 mΩ dissipates 1 W at 10 A. Calculate P = I²·R.",
  ]),
  related: ['transistor-basics', 'transistor-switch', 'flyback-diode'],
  seeAlso: [],
};

// ─────────────────────────────────────────────────────────────────────────────
// INTEGRATED CIRCUITS
// ─────────────────────────────────────────────────────────────────────────────

const opampBasics: KBArticle = {
  id: 'opamp-basics',
  title: 'Op-Amps: The Universal Amplifier',
  category: 'ic',
  tags: ['opamp', 'amplifier', 'feedback', 'golden-rules', 'analog'],
  summary: 'An op-amp amplifies the difference between its two inputs by a huge factor (~100,000×). With negative feedback, it becomes a precise, predictable circuit element.',
  body: body([
    "# Operational Amplifiers (Op-Amps)",
    "",
    "## The Symbol",
    "",
    "          ┌─────┐",
    "  V+ ────→│ +   │",
    "          │     ├────→ V_out",
    "  V− ────→│ −   │",
    "          └─────┘",
    "            │ │",
    "           V+ V− (power rails, usually hidden)",
    "",
    "## The Two Golden Rules (with negative feedback)",
    "",
    "1. **No current flows into the inputs.** (Input impedance is essentially infinite.)",
    "2. **The op-amp adjusts V_out to make V+ = V−.** (Negative feedback forces the inputs to the same voltage.)",
    "",
    "These two rules solve 90% of op-amp circuits.",
    "",
    "## Key Parameters",
    "",
    "| Parameter | Ideal | LM358 (typical) |",
    "|---|---|---|",
    "| Open-loop gain | ∞ | 100,000 |",
    "| Input impedance | ∞ | 1 MΩ (LM358), 10¹² Ω (TL072, JFET) |",
    "| Output impedance | 0 | 100 Ω |",
    "| Bandwidth | ∞ | 1 MHz (LM358), 3 MHz (TL072) |",
    "| Slew rate | ∞ | 0.5 V/µs (LM358), 13 V/µs (TL072) |",
    "| Offset voltage | 0 | 2 mV (LM358), 3 mV (TL072) |",
    "",
    "## Basic Circuits",
    "",
    "### 1. Voltage Follower (Buffer)",
    "  V_in ──→ +",
    "           │",
    "      V_out ──→ − (feedback)",
    "",
    "V_out = V_in",
    "",
    "**Use:** Isolate a high-impedance source from a low-impedance load.",
    "",
    "### 2. Inverting Amplifier",
    "  V_in ──[R_in]──→ −",
    "                   │",
    "              [R_f]",
    "                   │",
    "              V_out",
    "",
    "  GND ──→ +",
    "",
    "**Gain = −R_f / R_in**",
    "",
    "### 3. Non-Inverting Amplifier",
    "  V_in ──→ +",
    "           │",
    "      V_out ──[R_f]──→ −",
    "                   │",
    "                  [R_g]",
    "                   │",
    "                  GND",
    "",
    "**Gain = 1 + R_f / R_g**",
    "",
    "### 4. Differential Amplifier",
    "  V1 ──[R]──→ −",
    "              │",
    "         [R_f]",
    "              │",
    "         V_out",
    "",
    "  V2 ──[R]──→ +",
    "              │",
    "         [R]  (to GND)",
    "",
    "**V_out = (V2 − V1) · R_f / R** (when all four resistors match)",
    "",
    "## Worked Example: Non-Inverting Amp with Gain 10",
    "",
    "Gain = 1 + R_f/R_g = 10 → R_f/R_g = 9.",
    "",
    "If R_g = 1 kΩ, R_f = 9 kΩ (use 9.1 kΩ standard, gain = 10.1).",
    "",
    "## Power Supply Considerations",
    "",
    "- **Dual supply (±V):** V+ = +12 V, V− = −12 V. Output can swing ±10 V. Classic for audio.",
    "- **Single supply:** V+ = 5 V, V− = GND. Output swings 0 to ~3.5 V (LM358). Must bias the input to mid-supply (V_cc/2) for AC signals.",
    "",
    "## Common Mistakes",
    "",
    "1. **Exceeding input common-mode range** — LM358 inputs work from 0 V to V_cc−1.5 V.",
    "2. **Output can't reach the rails** — LM358 output max = V_cc−1.5 V. Use rail-to-rail op-amp (MCP6001) for full swing.",
    "3. **No decoupling capacitor** — op-amps oscillate without a 100 nF cap close to the power pin.",
    "4. **Bandwidth limit** — Gain × Bandwidth = GBW (1 MHz for LM358). At gain 100, bandwidth = 10 kHz.",
    "5. **Slew rate limit** — at high frequencies, the output can't change fast enough.",
  ]),
  related: [],
  seeAlso: ['transistor-basics'],
};

const timer555: KBArticle = {
  id: '555-timer',
  title: '555 Timer: The Universal Timer IC',
  category: 'ic',
  tags: ['555', 'timer', 'astable', 'monostable', 'oscillator', 'classic'],
  summary: 'The 555 is a timer/oscillator that can run in astable (oscillator) or monostable (one-shot) mode. With just 2 resistors and a capacitor, it generates clock signals from 1 Hz to 1 MHz.',
  body: body([
    "# The 555 Timer",
    "",
    "## The 8 Pins",
    "",
    "| Pin | Name | Function |",
    "|---|---|---|",
    "| 1 | GND | Ground |",
    "| 2 | TRIG | Trigger (starts timing when < ⅓V_cc) |",
    "| 3 | OUT | Output (push-pull, sources or sinks up to 200 mA) |",
    "| 4 | RESET | Active low (connect to V_cc if unused) |",
    "| 5 | CTRL | Control voltage (⅔V_cc reference; bypass with 100 nF) |",
    "| 6 | THR | Threshold (ends timing when > ⅔V_cc) |",
    "| 7 | DIS | Discharge (open collector, discharges timing cap) |",
    "| 8 | V_cc | Supply (4.5-16 V for NE555, 2-15 V for TLC555 CMOS) |",
    "",
    "## Mode 1: Astable (Oscillator)",
    "",
    "  V_cc ──[R1]──┬──[R2]──┐",
    "               │         │",
    "               ├── Pin 7 (DIS)",
    "               │",
    "              [C]  ← timing capacitor",
    "               │",
    "              GND",
    "",
    "  Pin 2 (TRIG) and Pin 6 (THR) tied together at the capacitor.",
    "",
    "### Formulas",
    "",
    "- **t_high** = 0.693 · (R1 + R2) · C",
    "- **t_low** = 0.693 · R2 · C",
    "- **Period** T = 0.693 · (R1 + 2·R2) · C",
    "- **Frequency** f = 1.44 / ((R1 + 2·R2) · C)",
    "- **Duty cycle** = (R1 + R2) / (R1 + 2·R2) — always > 50%",
    "",
    "### Worked Example: 1 Hz Blinker",
    "",
    "Want f = 1 Hz, C = 10 µF.",
    "",
    "R1 + 2·R2 = 1.44 / (1 · 10e−6) = 144,000 Ω",
    "",
    "Pick R2 = 47 kΩ → R1 = 144k − 94k = 50 kΩ (use 47 kΩ).",
    "",
    "Recalculate: f = 1.44 / ((47000 + 94000) · 10e−6) = 1.02 Hz.",
    "",
    "## Mode 2: Monostable (One-Shot)",
    "",
    "  V_cc ──[R]──┬── Pin 6/7",
    "              [C]",
    "              GND",
    "",
    "  Trigger: Pin 2 pulled low momentarily.",
    "",
    "### Formula",
    "",
    "**t_pulse = 1.1 · R · C**",
    "",
    "### Example: 10-Second Timer",
    "",
    "C = 100 µF, R = ?",
    "",
    "R = 10 / (1.1 · 100e−6) = 91 kΩ → use 100 kΩ.",
    "",
    "t = 1.1 · 100000 · 100e−6 = 11 seconds.",
    "",
    "## Common Mistakes",
    "",
    "1. **Pin 5 floating** — always bypass CTRL (pin 5) with a 100 nF cap to GND.",
    "2. **RESET floating** — pin 4 is active low. Tie to V_cc if unused.",
    "3. **Big electrolytic + high R** — leakage current in electrolytics exceeds the charging current.",
    "4. **Too high frequency** — bipolar NE555 tops out around 100 kHz. Use CMOS TLC555 for MHz.",
    "5. **Driving heavy loads** — buffer with a transistor for > 100 mA loads.",
    "",
    "## Variants",
    "",
    "| Part | Type | V_cc range | Max freq |",
    "|---|---|---|---|",
    "| NE555 | Bipolar | 4.5-16 V | 100 kHz |",
    "| TLC555 | CMOS | 2-15 V | 2 MHz |",
    "| LMC555 | CMOS | 1.5-15 V | 3 MHz |",
  ]),
  related: ['capacitor-basics'],
  seeAlso: ['transistor-switch'],
};

// ─────────────────────────────────────────────────────────────────────────────
// TROUBLESHOOTING
// ─────────────────────────────────────────────────────────────────────────────

const floatingNode: KBArticle = {
  id: 'floating-node',
  title: 'Floating Node: "Singular Matrix" Error',
  category: 'troubleshooting',
  tags: ['floating', 'singular-matrix', 'dc', 'error', 'convergence', 'ground'],
  summary: 'A floating node has no DC path to ground. The simulator can\'t determine its voltage and returns "singular matrix". Fix: add a high-value resistor (1 MΩ) from the node to ground.',
  body: body([
    "# Floating Node",
    "",
    "## The Error",
    "",
    "When you run a DC or transient simulation, you may see:",
    "",
    "> Singular matrix. Check for: (1) floating nodes, (2) voltage source loops, (3) capacitor-only branches.",
    "",
    "## What Is a Floating Node?",
    "",
    "A floating node is a node that has **no DC path to ground**. The simulator can't determine its voltage because there's no reference.",
    "",
    "### Common Causes",
    "",
    "1. **Capacitor in series with a signal** — DC can't pass through a cap.",
    "2. **Open switch** — a node behind an open switch has no DC path.",
    "3. **Unconnected input pin** — an op-amp input with nothing connected.",
    "4. **Transformer secondary** — the secondary side is galvanically isolated.",
    "",
    "## How to Fix",
    "",
    "### Fix 1: Add a High-Value Resistor to Ground",
    "",
    "Add a 1 MΩ to 10 MΩ resistor from the floating node to ground. This provides a DC path without significantly affecting circuit operation.",
    "",
    "### Fix 2: Connect the Inputs",
    "",
    "If an op-amp input is floating, connect it to a real signal or to ground.",
    "",
    "### Fix 3: Add a Ground on the Secondary",
    "",
    "For transformer-coupled circuits, add a ground on the secondary side.",
    "",
    "## How to Diagnose",
    "",
    "1. **Look at the error message** — it usually mentions the node number.",
    "2. **Trace the node** — follow every wire. If you can't reach ground through resistors or voltage sources, it's floating.",
    "3. **Check capacitors** — caps block DC. If a node is only connected through caps, it floats.",
    "4. **Check switches** — open switches break DC paths.",
    "5. **Use the AI Diagnose tool** — it can identify floating nodes automatically.",
    "",
    "## Related Errors",
    "",
    "- **Voltage source loop** — two ideal voltage sources in parallel. Fix: add a small series resistor (1 mΩ).",
    "- **Capacitor-only loop** — a loop with only capacitors. Fix: add a series resistor.",
    "- **Inductor loop** — a loop of only inductors. Fix: add a series resistor.",
  ]),
  related: ['missing-ground', 'capacitor-basics', 'dc-operating-point'],
  seeAlso: ['parallel-voltage-sources', 'convergence-issues'],
};

const missingGround: KBArticle = {
  id: 'missing-ground',
  title: 'Missing Ground Reference',
  category: 'troubleshooting',
  tags: ['ground', 'reference', 'error', 'fundamental', 'dc'],
  summary: 'Every circuit needs a ground (0 V reference). Without it, the simulator can\'t solve any voltages. Always add a Ground component.',
  body: body([
    "# Missing Ground",
    "",
    "## The Error",
    "",
    "The simulator refuses to run, or all voltages show as 0 V / NaN.",
    "",
    "## Why You Need Ground",
    "",
    "Voltage is always **relative**. Saying 'this node is at 5 V' means '5 V above ground'. Without a defined ground (0 V reference), the simulator has no anchor — every voltage is undefined.",
    "",
    "## How to Add Ground",
    "",
    "1. Open the component palette.",
    "2. Find the 'Ground' or 'Power' category.",
    "3. Click 'Ground' (or GND power port).",
    "4. Place it on the canvas.",
    "5. Wire it to the negative terminal of your voltage source and to one side of every load.",
    "",
    "## Using Power Port Symbols",
    "",
    "For larger circuits, you don't need to wire every ground back to a single point. Use power port symbols:",
    "- **GND** — all GND symbols are connected automatically.",
    "- **VCC** — all VCC symbols are connected.",
    "- **+5V**, **+3V3**, etc. — power rails.",
    "",
    "This keeps the schematic clean.",
    "",
    "## Grounding Best Practices",
    "",
    "1. **Single-point ground** (star ground) for analog circuits.",
    "2. **Separate analog and digital grounds** — AGND and DGND, connected at one point.",
    "3. **Ground plane on PCB** — a whole copper layer devoted to ground.",
    "4. **Decoupling caps close to ICs** — bypass noise to ground locally.",
    "",
    "## Common Mistakes",
    "",
    "1. **Forgetting to wire the voltage source's negative terminal to ground** — the source floats.",
    "2. **Multiple 'ground' symbols that aren't actually connected** — in this simulator, all GND power ports are auto-connected.",
    "3. **Grounding the wrong side of a current source** — current sources have no inherent reference.",
    "4. **No ground on the secondary of a transformer** — the secondary is isolated; add a ground reference.",
  ]),
  related: ['floating-node', 'voltage-divider', 'dc-operating-point'],
  seeAlso: ['decoupling'],
};

const convergenceIssues: KBArticle = {
  id: 'convergence-issues',
  title: 'Convergence Issues: "No Convergence" Error',
  category: 'troubleshooting',
  tags: ['convergence', 'newton-raphson', 'nonlinear', 'diode', 'transistor', 'error'],
  summary: 'Nonlinear components (diodes, transistors) can prevent the Newton-Raphson solver from converging. Fixes: add series resistance, use realistic initial conditions, or enable gmin stepping.',
  body: body([
    "# Convergence Issues",
    "",
    "## The Error",
    "",
    "The simulator fails to find a DC operating point, or transient simulation stalls at a particular timestep.",
    "",
    "## Why It Happens",
    "",
    "The simulator uses **Newton-Raphson iteration** to solve nonlinear circuits. Starting from an initial guess, it iteratively refines the solution. If the initial guess is too far off, or the circuit has a very steep nonlinearity, the iteration may oscillate or diverge.",
    "",
    "### Common Culprits",
    "",
    "1. **Diodes/LEDs with no series resistance** — the I-V curve is exponential.",
    "2. **Ideal voltage source across a diode** — V = 0.7 V exactly, but the simulator tries 5 V → enormous current → divergence.",
    "3. **Floating nodes** — see 'Floating Node' article.",
    "4. **Voltage source loops** — two ideal sources in parallel.",
    "5. **No initial condition on oscillators** — the simulator starts at V = 0 everywhere.",
    "",
    "## How to Fix",
    "",
    "### Fix 1: Add Series Resistance (most common fix)",
    "",
    "Add a small resistor (1 Ω to 100 Ω) in series with diodes, LEDs, and voltage sources.",
    "",
    "Before (won't converge):",
    "  5 V ──[LED]── GND",
    "",
    "After (converges):",
    "  5 V ──[330 Ω]──[LED]── GND",
    "",
    "### Fix 2: Use Realistic Voltage Sources",
    "",
    "Real voltage sources have internal resistance. Add a 1 Ω series resistor.",
    "",
    "### Fix 3: Add Initial Conditions",
    "",
    "For oscillators, set initial node voltages to a non-zero starting point.",
    "",
    "### Fix 4: Increase Iterations",
    "",
    "The default max iterations is 50. Increase to 500 or 1000 for difficult circuits.",
    "",
    "## Specific Problem Circuits",
    "",
    "### Ring Modulator / Diode Bridge",
    "Four diodes in a bridge. Fix: Add 1 kΩ in series with each diode.",
    "",
    "### Crystal Oscillator",
    "No DC operating point exists. Fix: Use initial conditions or pseudo-transient.",
    "",
    "### Switching Regulator",
    "Switch transitions are instantaneous. Fix: Add a small capacitor across the switch.",
    "",
    "## Diagnosing",
    "",
    "1. **Look at the error message** — it often mentions the problematic node.",
    "2. **Remove nonlinear components** — replace diodes with resistors. If it converges, nonlinearity is the problem.",
    "3. **Add series resistance** — the universal fix.",
    "4. **Use the AI Diagnose tool** — it can identify convergence issues automatically.",
  ]),
  related: ['floating-node', 'missing-ground', 'dc-operating-point', 'diode-basics'],
  seeAlso: ['transistor-basics'],
};

const parallelVoltageSources: KBArticle = {
  id: 'parallel-voltage-sources',
  title: 'Parallel Voltage Sources: "Voltage Source Loop" Error',
  category: 'troubleshooting',
  tags: ['voltage-source', 'loop', 'singular-matrix', 'error', 'dc'],
  summary: 'Two ideal voltage sources in parallel create a loop with no resistance. The simulator can\'t solve the current. Fix: add a small series resistor (1 mΩ) to one source.',
  body: body([
    "# Parallel Voltage Sources",
    "",
    "## The Error",
    "",
    "> Singular matrix. Check for: (2) voltage source loops.",
    "",
    "## What's a Voltage Source Loop?",
    "",
    "An ideal voltage source has zero internal resistance. If you connect two in parallel:",
    "",
    "  V1 (5V) ──┬── V2 (5V)",
    "            │",
    "          Node A",
    "",
    "If V1 and V2 are both exactly 5 V, current flows but is **undetermined**.",
    "",
    "If V1 = 5 V and V2 = 5.001 V, the current is **infinite** (I = 0.001 / 0 = ∞).",
    "",
    "Both cases make the matrix singular.",
    "",
    "## Common Causes",
    "",
    "1. **Parallel batteries** — two 9 V batteries in parallel.",
    "2. **Multiple regulators** — two LM7805s feeding the same 5 V rail.",
    "3. **Voltage source + inductor loop** — an inductor is a short at DC.",
    "4. **Voltage source + capacitor loop** — same issue at the instant of connection.",
    "",
    "## How to Fix",
    "",
    "### Fix 1: Add Series Resistance",
    "",
    "Add a small resistor (1 mΩ to 1 Ω) in series with one of the sources.",
    "",
    "### Fix 2: Use a Single Source",
    "",
    "If both sources are meant to be the same voltage, just use one source.",
    "",
    "### Fix 3: Add Resistance to the Inductor",
    "",
    "Real inductors have DC resistance (DCR). Set the inductor's series resistance to a realistic value.",
    "",
    "## Why This Matters in Real Life",
    "",
    "Parallel voltage sources are bad practice in real circuits too:",
    "- Two batteries in parallel will charge/discharge each other.",
    "- Two regulators in parallel can oscillate or one can hog the load.",
    "",
    "Use **current sharing resistors** (0.1-0.5 Ω) in series with each source.",
  ]),
  related: ['floating-node', 'convergence-issues'],
  seeAlso: ['inductor-basics'],
};

// ─────────────────────────────────────────────────────────────────────────────
// DESIGN PATTERNS
// ─────────────────────────────────────────────────────────────────────────────

const decoupling: KBArticle = {
  id: 'decoupling',
  title: 'Decoupling (Bypass) Capacitors',
  category: 'design-patterns',
  tags: ['decoupling', 'bypass', 'capacitor', 'power-supply', 'noise', 'ic'],
  summary: 'Every IC needs a 100 nF capacitor close to its power pin to supply transient current and filter high-frequency noise. Without it, the IC may reset, oscillate, or behave erratically.',
  body: body([
    "# Decoupling Capacitors",
    "",
    "## Why You Need Them",
    "",
    "When an IC switches state, it draws a sudden spike of current from the power supply. The power supply and traces have inductance, which opposes current changes. The result: the supply voltage at the IC **dips** momentarily.",
    "",
    "If the dip is large enough:",
    "- The IC resets",
    "- The IC outputs glitches",
    "- Analog circuits pick up noise",
    "",
    "A decoupling capacitor acts as a **local energy reservoir**.",
    "",
    "## The Standard Practice",
    "",
    "**Place a 100 nF (0.1 µF) ceramic capacitor as close as possible to every IC's V_cc pin, connecting V_cc to GND.**",
    "",
    "For ICs with multiple V_cc pins, use one cap per pin.",
    "",
    "## Why 100 nF?",
    "",
    "- **Low ESR** — responds fast to transients",
    "- **Low inductance** — smaller caps (0402/0603 SMD) have less inductance",
    "- **Sufficient charge** for microsecond-scale transients",
    "",
    "## Bulk Capacitors",
    "",
    "In addition to the 100 nF per IC, add a **bulk capacitor** (10 µF to 100 µF electrolytic) at the power supply input.",
    "",
    "## The Two-Cap Strategy",
    "",
    "  Power Supply ──┬──[10 µF]── GND  (bulk)",
    "                 │",
    "                 ├──[100 nF]── GND  (per IC, close to pin)",
    "                 │",
    "                IC V_cc",
    "",
    "- **10 µF** handles low-frequency ripple",
    "- **100 nF** handles high-frequency transients",
    "",
    "## Placement",
    "",
    "**Closer is better.** The trace from the cap to the IC's V_cc pin should be as short as possible — ideally < 5 mm.",
    "",
    "Why? Trace inductance. A 10 mm trace has ~10 nH of inductance. At 100 MHz, that's 6.3 Ω of reactance.",
    "",
    "## Common Mistakes",
    "",
    "1. **No decoupling cap** — IC resets or oscillates randomly.",
    "2. **Cap too far from IC** — trace inductance defeats the purpose.",
    "3. **Only bulk, no ceramic** — bulk cap has high ESR.",
    "4. **Only ceramic, no bulk** — ceramic cap has low capacity.",
    "5. **Wrong dielectric** — Y5V ceramic loses 80% of capacitance over temperature. Use X7R or C0G.",
    "",
    "## How to Choose",
    "",
    "| IC Type | Decoupling |",
    "|---|---|",
    "| Logic (74xx, CD40xx) | 100 nF per IC |",
    "| Microcontroller | 100 nF per V_cc pin + 10 µF bulk |",
    "| Op-amp | 100 nF per op-amp |",
    "| FPGA | 100 nF per V_cc + 4.7 µF per bank + 47 µF bulk |",
    "| RF IC | 100 pF + 10 nF + 1 µF (multi-value) |",
  ]),
  related: ['capacitor-basics', 'pcb-layout-basics'],
  seeAlso: ['ground-plane'],
};

const transistorSwitch: KBArticle = {
  id: 'transistor-switch',
  title: 'Transistor as a Switch',
  category: 'design-patterns',
  tags: ['transistor', 'switch', 'bjt', 'mosfet', 'digital', 'design-pattern'],
  summary: 'Drive a transistor into saturation (fully ON) or cutoff (fully OFF) to switch loads. BJTs need base current; MOSFETs need gate voltage.',
  body: body([
    "# Transistor as a Switch",
    "",
    "## The Concept",
    "",
    "A transistor has three regions: cutoff (OFF), active (amplifier), and saturation (ON). For switching, we only use cutoff and saturation — never the active region.",
    "",
    "## BJT Switch (NPN)",
    "",
    "  V+ (load supply) ──[Load]── Collector",
    "                                │",
    "                            NPN (Q1)",
    "                                │",
    "                              GND ── Emitter",
    "",
    "  Control ──[R_base]── Base",
    "",
    "### Design Steps",
    "",
    "1. **Determine load current** I_load.",
    "2. **Choose a transistor** with I_C(max) > I_load.",
    "3. **Calculate base current** I_B = I_load / h_FE(min).",
    "4. **Overdrive by 2-5×** for guaranteed saturation.",
    "5. **Calculate base resistor** R_base = (V_control − 0.7) / I_B_actual.",
    "",
    "## MOSFET Switch (NMOS, Low-Side)",
    "",
    "  V+ ──[Load]── Drain",
    "                 │",
    "             NMOS (Q1)",
    "                 │",
    "               GND ── Source",
    "",
    "  Control ──[R_gate]── Gate",
    "                 │",
    "             [R_pulldown] (10k to GND)",
    "",
    "### Design Steps",
    "",
    "1. **Determine load current** I_load.",
    "2. **Choose a logic-level MOSFET** with R_DS(on) low enough.",
    "3. **Add a gate pulldown** (10 kΩ).",
    "4. **Add a gate resistor** (100-220 Ω).",
    "",
    "## Common BJT Choices",
    "",
    "| Transistor | I_C(max) | h_FE(min) | Use |",
    "|---|---|---|---|",
    "| 2N3904 | 200 mA | 50 | Small signals, LEDs |",
    "| 2N2222 | 600 mA | 50 | Small loads, relays |",
    "| BC547 | 100 mA | 110 | Small signals |",
    "| TIP122 (Darlington) | 5 A | 1000 | Motors, high current |",
    "",
    "## Common MOSFET Choices",
    "",
    "| MOSFET | I_D(max) | R_DS(on) | V_GS(th) | Use |",
    "|---|---|---|---|---|",
    "| 2N7000 | 200 mA | 5 Ω | 2.1 V | Small signals |",
    "| IRLZ44N | 47 A | 28 mΩ | 1-2 V | Logic-level, medium power |",
    "| IRF540N | 33 A | 44 mΩ | 2-4 V | Standard (needs 10 V gate) |",
    "| IRLB8721 | 62 A | 6.5 mΩ | 1-2 V | Logic-level, high power |",
    "",
    "## Why MOSFETs Are Usually Better for Switching",
    "",
    "1. **No gate current** — doesn't load the MCU pin.",
    "2. **Lower R_DS(on)** — less voltage drop, less heat.",
    "3. **Faster switching** — no storage time.",
    "4. **Easier to parallel** — positive temperature coefficient.",
    "",
    "## Common Mistakes",
    "",
    "1. **Not saturating (BJT)** — if I_B is too low, V_CE is high and the transistor overheats.",
    "2. **Non-logic-level MOSFET with 3.3 V MCU** — MOSFET never fully turns on.",
    "3. **No gate pulldown (MOSFET)** — MOSFET turns on randomly during MCU reset.",
    "4. **No flyback diode for inductive loads** — voltage spike kills the transistor.",
    "5. **Exceeding I_C(max) or I_D(max)** — transistor dies.",
    "6. **No heatsink for high power** — even R_DS(on) = 50 mΩ dissipates 5 W at 10 A.",
  ]),
  related: ['transistor-basics', 'mosfet-basics', 'led-current-limiting', 'flyback-diode'],
  seeAlso: [],
};

const flybackDiode: KBArticle = {
  id: 'flyback-diode',
  title: 'Flyback (Freewheeling) Diode',
  category: 'design-patterns',
  tags: ['diode', 'inductor', 'protection', 'flyback', 'relay', 'motor', 'spike'],
  summary: 'When an inductive load (relay, motor, solenoid) is switched off, the collapsing magnetic field generates a high-voltage spike. A flyback diode clamps this spike.',
  body: body([
    "# Flyback Diode",
    "",
    "## The Problem",
    "",
    "An inductor stores energy in its magnetic field. The voltage across an inductor is:",
    "",
    "**V = −L · dI/dt**",
    "",
    "When you interrupt the current (turn off the switch), dI/dt is very large and negative. The voltage spikes to hundreds or thousands of volts.",
    "",
    "### Example",
    "",
    "A 100 mH relay coil carrying 100 mA is switched off in 1 µs.",
    "",
    "V = −0.1 · (−0.1 / 1e−6) = 10,000 V",
    "",
    "This voltage appears across the switch. It will:",
    "- Avalanche the transistor (likely destroy it)",
    "- Arc across relay contacts (pit them)",
    "",
    "## The Solution: Flyback Diode",
    "",
    "Place a diode across the inductor, cathode to V+. During normal operation, the diode is reverse-biased (off). When the switch opens, the inductor's voltage reverses, the diode becomes forward-biased, and the current circulates through the diode-inductor loop.",
    "",
    "  V+ ──[Relay Coil]──┬── Switch ── GND",
    "                     │",
    "                   [Diode]  ← cathode to V+ side",
    "",
    "## Choosing the Diode",
    "",
    "| Parameter | Requirement |",
    "|---|---|",
    "| V_R(max) | > V+ |",
    "| I_F(avg) | > I_coil |",
    "| I_F(surge) | > I_coil |",
    "| t_rr | Not critical for relay; critical for SMPS |",
    "",
    "**Typical choices:**",
    "- **1N4148** — small relays (< 100 mA)",
    "- **1N4001-1N4007** — most relays",
    "- **Schottky (1N5817)** — SMPS, fast switching",
    "",
    "## Alternatives",
    "",
    "### TVS Diode",
    "Clamps at a specific voltage. Better if you need the voltage to rise (e.g. to brake a motor quickly).",
    "",
    "### RC Snubber",
    "A resistor + capacitor in series across the switch. Used when a diode would slow the release too much.",
    "",
    "### Zener + Diode",
    "Allows the voltage to rise to the zener voltage before clamping. Faster relay release.",
    "",
    "## Common Mistakes",
    "",
    "1. **Diode backwards** — shorts the supply through the coil. Diode smokes.",
    "2. **Diode too small** — I_F(surge) exceeded, diode fails short.",
    "3. **No diode on a motor** — transistor dies.",
    "4. **Using a slow diode in a SMPS** — use Schottky or ultra-fast recovery.",
    "5. **Forgetting the diode on relay contacts** — arcing pits the contacts.",
  ]),
  related: ['inductor-basics', 'diode-basics', 'transistor-switch', 'mosfet-basics'],
  seeAlso: [],
};

// ─────────────────────────────────────────────────────────────────────────────
// PCB LAYOUT
// ─────────────────────────────────────────────────────────────────────────────

const pcbLayoutBasics: KBArticle = {
  id: 'pcb-layout-basics',
  title: 'PCB Layout Fundamentals',
  category: 'pcb',
  tags: ['pcb', 'layout', 'design-rules', 'manufacturing', 'jlcpcb'],
  summary: 'PCB layout turns a schematic into a physical board. Key concerns: trace width for current, clearance for voltage, component placement, and manufacturing constraints.',
  body: body([
    "# PCB Layout Fundamentals",
    "",
    "## The Goal",
    "",
    "A PCB layout must:",
    "1. **Connect the right pads** (match the schematic netlist)",
    "2. **Carry the required current** without overheating",
    "3. **Insulate adjacent signals** by enough clearance",
    "4. **Be manufacturable** by standard PCB houses",
    "",
    "## Manufacturing Constraints (2-Layer, Standard Spec)",
    "",
    "| Parameter | Typical (JLCPCB) |",
    "|---|---|",
    "| Min trace width | 0.127 mm (5 mil) |",
    "| Min clearance | 0.127 mm (5 mil) |",
    "| Min drill | 0.2 mm |",
    "| Min annular ring | 0.127 mm |",
    "| Board thickness | 1.6 mm (standard) |",
    "| Copper weight | 1 oz (35 µm) |",
    "",
    "## Trace Width for Current",
    "",
    "| Current | Min trace width (1 oz Cu, 10°C rise) |",
    "|---|---|",
    "| 0.5 A | 0.2 mm (8 mil) |",
    "| 1 A | 0.4 mm (16 mil) |",
    "| 2 A | 0.8 mm (32 mil) |",
    "| 3 A | 1.5 mm (60 mil) |",
    "| 5 A | 3.0 mm (120 mil) |",
    "| 10 A | Use a plane or 2 oz copper |",
    "",
    "For high current, use **polygons** (copper pours) instead of traces.",
    "",
    "## Clearance for Voltage",
    "",
    "| Voltage | Min clearance |",
    "|---|---|",
    "| < 30 V | 0.15 mm (6 mil) |",
    "| 30-50 V | 0.25 mm (10 mil) |",
    "| 50-150 V | 0.6 mm (24 mil) |",
    "| 150-300 V | 1.5 mm (60 mil) |",
    "",
    "## Component Placement",
    "",
    "### Hierarchy",
    "1. **Connectors** on the board edge",
    "2. **Mechanical components** (switches, displays) in fixed locations",
    "3. **Critical ICs** (closest to their connectors)",
    "4. **Support components** (decoupling caps) right next to their ICs",
    "5. **Passive components** in remaining space",
    "",
    "### Rules of Thumb",
    "- **Decoupling caps within 5 mm of the IC's V_cc pin**",
    "- **Crystal next to the microcontroller**",
    "- **Analog away from digital**",
    "- **High-frequency away from board edges**",
    "",
    "## Layer Stackup (2-Layer)",
    "",
    "  Top silk       ← component labels",
    "  Top solder mask ← green protective layer",
    "  Top copper     ← signals, components",
    "  ─── FR4 (1.6 mm) ───",
    "  Bottom copper  ← ground plane, signals",
    "  Bottom solder mask",
    "  Bottom silk",
    "",
    "**Best practice:** Bottom layer is a solid ground plane. All signals on top.",
    "",
    "## Routing Rules",
    "",
    "1. **Route power first** — wide traces, direct paths",
    "2. **Route high-speed signals next** — short, direct, no vias",
    "3. **Route low-speed signals last**",
    "4. **Use vias sparingly** — each via adds inductance",
    "5. **Don't route under sensitive components**",
    "",
    "## Grounding",
    "",
    "### Ground Plane",
    "A whole copper layer devoted to ground. Always use one if you have ≥ 2 layers.",
    "",
    "### Star Ground",
    "All ground connections meet at a single point. Used in analog circuits.",
    "",
    "### Split Ground",
    "Separate AGND and DGND planes, connected at one point.",
    "",
    "## Common Mistakes",
    "",
    "1. **Traces too thin for current** — overheats, voltage drop.",
    "2. **Decoupling cap too far from IC** — inductance defeats the purpose.",
    "3. **No ground plane** — high ground impedance, EMI.",
    "4. **Routing analog through digital** — noise coupling.",
    "5. **Vias in pads** — wicks solder away.",
    "6. **Silkscreen on pads** — prevents soldering.",
    "7. **No mounting holes** — board needs to be secured.",
    "8. **Components too close to the edge** — fab house may clip them.",
  ]),
  related: ['decoupling', 'ground-plane'],
  seeAlso: [],
};

const groundPlane: KBArticle = {
  id: 'ground-plane',
  title: 'Ground Planes: The Foundation of Good PCB Design',
  category: 'pcb',
  tags: ['ground', 'plane', 'pcb', 'emi', 'signal-integrity'],
  summary: 'A ground plane is a solid copper layer devoted to ground. It provides low-impedance return paths, reduces EMI, and stabilizes voltages.',
  body: body([
    "# Ground Planes",
    "",
    "## What Is a Ground Plane?",
    "",
    "A ground plane is a solid (or nearly solid) sheet of copper on a PCB layer, connected to the ground net.",
    "",
    "## Why You Need One",
    "",
    "### 1. Low Impedance Return Path",
    "Every signal trace has a return current. With a ground plane, the return current flows **directly under the signal trace** — minimizing loop area and radiated EMI.",
    "",
    "### 2. Stable Voltage Reference",
    "A ground plane has very low resistance and inductance. All ground points are at (approximately) the same voltage.",
    "",
    "### 3. EMI Reduction",
    "Small loop areas act as poor antennas. Less EMI is radiated and picked up.",
    "",
    "### 4. Decoupling Effect",
    "The ground plane has parasitic capacitance to signal traces, providing additional high-frequency decoupling.",
    "",
    "## How to Use a Ground Plane",
    "",
    "### 2-Layer Board",
    "- **Bottom layer:** ground plane (as solid as possible)",
    "- **Top layer:** signals and components",
    "- Use vias to connect top-layer ground pins to the bottom plane",
    "",
    "### 4-Layer Board",
    "- **Layer 1 (top):** signals and components",
    "- **Layer 2:** ground plane (solid, no traces)",
    "- **Layer 3:** power plane",
    "- **Layer 4 (bottom):** signals and components",
    "",
    "## What NOT to Do",
    "",
    "### 1. Don't Cut the Plane with Traces",
    "A trace on the ground plane layer splits it into two islands. Return currents must detour.",
    "",
    "### 2. Don't Create Islands",
    "If a section of the plane is surrounded by traces, it's not connected to the rest of the ground.",
    "",
    "### 3. Don't Use Multiple Grounds Without Thinking",
    "Splitting AGND and DGND can help, but only if done correctly:",
    "- Connect them at **one point** (usually under the ADC)",
    "- Don't route signals across the split",
    "",
    "### 4. Don't Forget the Return Path for High-Speed Signals",
    "If you route a signal through a via to another layer, the return current must also find a via. Provide a ground via next to every signal via.",
  ]),
  related: ['decoupling', 'pcb-layout-basics'],
  seeAlso: [],
};

// ─────────────────────────────────────────────────────────────────────────────
// ANALYSIS
// ─────────────────────────────────────────────────────────────────────────────

const dcOperatingPoint: KBArticle = {
  id: 'dc-operating-point',
  title: 'DC Operating Point (.op / DC Bias)',
  category: 'analysis',
  tags: ['dc', 'operating-point', 'bias', 'analysis', 'simulation'],
  summary: 'The DC operating point is the steady-state voltages and currents when all transients have settled. It\'s the starting point for AC analysis and the bias point for transistors.',
  body: body([
    "# DC Operating Point",
    "",
    "## What It Is",
    "",
    "The DC operating point (Q-point) is the steady-state solution of a circuit:",
    "- All capacitors are open (no current flows)",
    "- All inductors are short (wire)",
    "- All sources are at their DC values",
    "- All transistors are in their steady-state region",
    "",
    "## Why It Matters",
    "",
    "### 1. Bias for Transistors",
    "A transistor amplifier needs to be biased so that:",
    "- The collector voltage is mid-supply (max symmetric swing)",
    "- The base-emitter voltage is ~0.7 V (forward-biased)",
    "- The transistor is in the active region",
    "",
    "### 2. Starting Point for AC Analysis",
    "AC analysis linearizes the circuit around the DC operating point. If the bias is wrong, the AC analysis is meaningless.",
    "",
    "### 3. Starting Point for Transient",
    "Transient simulation starts from the DC operating point.",
    "",
    "### 4. Power Dissipation",
    "The DC power dissipation P = V × I tells you what will heat up.",
    "",
    "## How to Analyze by Hand",
    "",
    "### Simple Circuits",
    "Apply Ohm's Law, KVL, KCL directly.",
    "",
    "### Transistor Circuits",
    "1. Assume V_BE = 0.7 V (silicon)",
    "2. Calculate I_B from the base circuit",
    "3. Calculate I_C = h_FE × I_B",
    "4. Calculate V_CE = V_CC − I_C × R_C",
    "5. Check that V_CE > 0.2 V (not saturated) and I_C > 0 (not cutoff)",
    "",
    "## Common Issues",
    "",
    "### 'No Convergence'",
    "The solver can't find a DC operating point. See 'Convergence Issues' article.",
    "",
    "### Wrong Region",
    "If the bias puts the transistor in cutoff or saturation, the amplifier doesn't amplify.",
    "",
    "### Temperature Sensitivity",
    "h_FE rises roughly +0.5 %/°C with temperature (the ~doubles-every-10 °C rule applies to leakage current I_CBO, not gain). Use emitter feedback to stabilize the operating point.",
  ]),
  related: ['ac-analysis', 'transient-analysis', 'convergence-issues'],
  seeAlso: ['floating-node'],
};

const acAnalysisArticle: KBArticle = {
  id: 'ac-analysis',
  title: 'AC Analysis (Frequency Response)',
  category: 'analysis',
  tags: ['ac', 'frequency', 'bode', 'analysis', 'simulation', 'small-signal'],
  summary: 'AC analysis computes the circuit\'s response to small sinusoidal signals across a frequency range. It produces Bode plots — essential for filters and amplifiers.',
  body: body([
    "# AC Analysis",
    "",
    "## What It Does",
    "",
    "AC analysis:",
    "1. Finds the DC operating point (bias)",
    "2. Linearizes all nonlinear components around that point",
    "3. Replaces each component with its small-signal model",
    "4. Solves the linear circuit at each frequency",
    "5. Returns magnitude and phase of any node voltage or branch current",
    "",
    "## When to Use It",
    "",
    "- **Filters:** Find cutoff frequency, rolloff slope, stopband attenuation",
    "- **Amplifiers:** Find bandwidth, gain vs. frequency",
    "- **Oscillators:** Verify the Barkhausen criterion",
    "- **Impedance matching:** Find input/output impedance",
    "",
    "## Setting Up an AC Analysis",
    "",
    "### 1. AC Source",
    "Use a voltage source with AC amplitude = 1 V.",
    "",
    "### 2. Frequency Sweep",
    "- **Decade sweep** (log frequency): 10 points per decade",
    "- **Start frequency, stop frequency**",
    "",
    "### 3. Output",
    "Plot magnitude (in dB) and phase (in degrees) — a **Bode plot**.",
    "",
    "## Reading a Bode Plot",
    "",
    "### Magnitude Plot",
    "- **Flat region:** the passband",
    "- **Rolloff:** where gain decreases (−20 dB/decade per pole)",
    "- **Cutoff frequency (f_c):** gain is −3 dB",
    "",
    "### Phase Plot",
    "- Each pole adds −45°/decade (−90° total)",
    "- Each zero adds +45°/decade (+90° total)",
    "",
    "## Worked Example: RC Low-Pass Filter",
    "",
    "  V_in (AC 1) ──[R = 1k]──┬── V_out",
    "                            [C = 1 µF]",
    "                            GND",
    "",
    "Cutoff: f_c = 1 / (2πRC) = 1 / (2π × 1000 × 1e−6) = 159 Hz",
    "",
    "## Stability",
    "",
    "For a feedback system to be stable:",
    "- At unity gain (0 dB), phase shift must be < −180°",
    "- **Phase margin** > 45° is usually safe",
    "",
    "## Common Issues",
    "",
    "1. **Transistor not supported** — some AC modules don't linearize transistors.",
    "2. **Wrong bias point** — AC analysis is only as good as the DC bias.",
    "3. **Source has no AC value** — add AC amplitude to the source.",
    "4. **Frequency range too narrow** — sweep wide enough to see the rolloff.",
  ]),
  related: ['dc-operating-point'],
  seeAlso: ['transient-analysis'],
};

const transientAnalysis: KBArticle = {
  id: 'transient-analysis',
  title: 'Transient Analysis (.tran)',
  category: 'analysis',
  tags: ['transient', 'time-domain', 'simulation', 'analysis'],
  summary: 'Transient analysis simulates the circuit\'s behavior over time. It shows how voltages and currents change as sources ramp, switch, or oscillate.',
  body: body([
    "# Transient Analysis",
    "",
    "## What It Does",
    "",
    "Transient analysis computes the circuit's response as a function of time:",
    "1. Find the DC operating point (initial condition)",
    "2. At each timestep, solve the circuit",
    "3. Advance time by dt, repeat",
    "",
    "## When to Use It",
    "",
    "- **Switching circuits:** relays, transistors turning on/off",
    "- **Oscillators:** verify frequency, amplitude, startup",
    "- **Charging/discharging:** RC/RL time constants",
    "- **Pulse response:** how does a filter respond to a step?",
    "- **Digital logic:** clock propagation, gate delays",
    "",
    "## Setting Up",
    "",
    "### 1. Time Step (dt)",
    "Choose dt to be at least 10× smaller than the fastest event:",
    "- 1 kHz signal: dt = 100 µs",
    "- 1 MHz signal: dt = 100 ns",
    "- 1 ns rise time: dt = 10 ps",
    "",
    "**Too large:** aliasing, missed events, inaccurate peaks.",
    "**Too small:** slow simulation, large file sizes.",
    "",
    "### 2. Stop Time",
    "Long enough to see steady state. For an oscillator, 10 periods is typical.",
    "",
    "## Reading the Waveform",
    "",
    "### 1. Steady State vs. Transient",
    "The first few cycles may be different from steady state. Wait for the transient to settle.",
    "",
    "### 2. Period and Frequency",
    "Measure the time between two identical points. f = 1/T.",
    "",
    "### 3. Amplitude",
    "Measure peak-to-peak (V_pp) or RMS (V_rms = V_pp / (2√2) for a sine).",
    "",
    "## Common Issues",
    "",
    "### 1. 'No Convergence at t = X'",
    "Usually caused by a nonlinear component with a steep I-V curve. Fix: add series resistance, reduce dt.",
    "",
    "### 2. Aliasing",
    "If dt is too large, high-frequency signals appear as low-frequency aliases.",
    "",
    "### 3. Numerical Damping",
    "Backward Euler integration damps oscillations. Use trap or Gear2 for better accuracy.",
    "",
    "## Comparison with AC Analysis",
    "",
    "| Aspect | Transient | AC |",
    "|---|---|---|",
    "| Domain | Time | Frequency |",
    "| Linearization | No (full nonlinear) | Yes (small-signal) |",
    "| Best for | Switching, large signals | Filters, bandwidth |",
    "| Speed | Slow | Fast |",
    "",
    "Use transient for large-signal or switching behavior. Use AC for linear frequency response.",
  ]),
  related: ['dc-operating-point', 'ac-analysis', 'capacitor-basics'],
  seeAlso: ['convergence-issues'],
};

const behavioralSources: KBArticle = {
  id: 'behavioral-sources',
  title: 'Behavioral Sources (B-Elements)',
  category: 'analysis',
  tags: ['behavioral', 'bvsource', 'bisource', 'expression', 'comparator', 'limiter', 'simulation'],
  summary: 'Behavioral sources (bvSource/biSource) define a voltage or current from an arbitrary expression — V(net), I(source), time, math functions, and comparisons — letting you build ideal amplifiers, comparators, limiters, and nonlinear blocks without transistors.',
  body: body([
    "# Behavioral Sources (B-Elements)",
    "",
    "## What They Are",
    "",
    "A behavioral source computes its output from an EXPRESSION instead of a fixed value:",
    "- **bvSource**: V(out) = expression (a voltage source)",
    "- **biSource**: I(out) = expression (a current source, positive from + through the source to −)",
    "",
    "## Expression Grammar",
    "",
    "- **V(net)**: voltage of a named net (name it with a netLabel). V(a,b) is the differential V(a) − V(b).",
    "- **I(sourceId)**: branch current of a voltage source, SPICE convention (negative when the source delivers power).",
    "- **time**: simulation time in seconds. **pi**: 3.14159…",
    "- Arithmetic: + − * / ^ and parentheses. Comparisons: > < >= <= == != (result 1 or 0).",
    "- Functions: sin cos tan exp log ln log10 abs sqrt min max limit(x, lo, hi) if(cond, a, b).",
    "",
    "## Classic Recipes",
    "",
    "- Ideal amplifier: 'V = 10*V(in)'",
    "- Comparator: 'V = if(V(in) > 2.5, 5, 0)'",
    "- Soft limiter: 'V = limit(V(in)*3, −5, 5)'",
    "- Ideal (rectifying) diode: 'V = if(V(in) > 0, V(in), 0)'",
    "- Current mirror: 'I = I(V1)*2'",
    "- Sine drive: 'V = sin(2*pi*1000*time)'",
    "",
    "## How the Simulator Solves Them",
    "",
    "Expressions that read V(net) or I(source) create implicit equations — the source's own output can influence its input. The engine runs a Gauss–Seidel iteration each timestep: stamp → solve → re-evaluate the expressions with the fresh node voltages → re-solve, until the solution stops moving. Oscillating fixed points (loop gain near −1) are damped automatically. Non-behavioral circuits pay zero cost.",
    "",
    "## Common Mistakes",
    "",
    "### 1. Referencing an unnamed net",
    "V(in) needs a netLabel with net name 'in' attached to that node — unnamed nodes read as 0V.",
    "",
    "### 2. Positive feedback without a limit",
    "'V = 10*V(out) + 0.1' has no finite solution. The engine caps the iteration and returns a bounded (but wrong) value. Always bound self-referencing expressions (limit(), a subtractive term, or a load that fights back).",
    "",
    "### 3. Infinite current from an ideal BV short",
    "A bvSource driving 5V into 0Ω is a singular matrix, exactly like a battery short. Give every behavioral output a load or series resistance.",
  ]),
  related: ['transient-analysis', 'dc-operating-point'],
  seeAlso: ['convergence-issues'],
};

const integrationMethods: KBArticle = {
  id: 'integration-methods',
  title: 'Integration Methods (Euler / Trapezoidal / Gear)',
  category: 'analysis',
  tags: ['integration', 'trapezoidal', 'gear', 'euler', 'numerical', 'oscillator', 'simulation'],
  summary: 'Capacitors and inductors are discretized by an integration method. Backward Euler is the most stable but adds artificial damping; trapezoidal (SPICE\'s default) is 2nd-order and conserves oscillator energy; Gear/BDF-2 adds controlled damping for stiff circuits.',
  body: body([
    "# Integration Methods",
    "",
    "## Why It Matters",
    "",
    "Every transient simulator replaces dv/dt and di/dt with a discrete approximation — the 'companion model'. The choice of approximation controls accuracy AND stability:",
    "",
    "| Method | Order | Stability | Energy behavior | Best for |",
    "|---|---|---|---|---|",
    "| Backward Euler | 1 | extremely (L-stable) | damps oscillators (lossy) | general switching, first pass |",
    "| Trapezoidal | 2 | A-stable | conserves energy exactly | oscillators, filters, resonance |",
    "| Gear (BDF-2) | 2 | A-stable | mild damping | stiff circuits, long transients |",
    "",
    "## The Classic Symptom",
    "",
    "An LC tank (L = 1 mH, C = 1 µF) charged to 5V should oscillate at f = 1/(2π√(LC)) ≈ 5 kHz forever. With backward Euler the amplitude decays to nothing within ~10 periods even though the circuit is lossless — the damping is NUMERICAL, an artifact of the 1st-order method. Run the same circuit with method='trap' and the amplitude stays constant.",
    "",
    "## Rules of Thumb",
    "",
    "- Resonant circuit (LC, crystal, tuned amplifier)? Use **trap**.",
    "- Mixed fast/slow time constants (power supply with 1µF and 100pF)? **gear** stays stable.",
    "- Digital switching with steep edges? **euler** tolerates large timesteps best.",
    "- Keep dt ≤ 1/20 of the signal period regardless of method.",
    "",
    "## Convergence Notes",
    "",
    "- The DC operating point always runs backward Euler (capacitors open, inductors short) — trap's voltage memory across the huge DC step would ring.",
    "- Gear starts at order 1 (Euler) for the first step, then ramps to BDF-2 — standard SPICE startup.",
    "- The engine runs a trapezoidal RINGING GUARD (LTspice 'modified trap' style): when a capacitor's current (or an inductor's voltage) shows a sustained (−1)^n alternation — the signature of trapezoidal ringing with dt >> tau or at sharp source edges — the element falls back to backward Euler for two steps, killing the mode. Genuine oscillation never trips it (a smooth sinusoid alternates at most once per extremum). A transient run reports the trip count as report.trapRings / scalars.trapRings; a large count suggests the timestep is too coarse for the circuit's time constants.",
    "- Switching the Integration Method in the Options dialog resets the transient (component state cleared, t=0 restart) — mid-run companion history is method-specific and would be numerically meaningless.",
    "- Try the 'LC Tank Oscillator' catalog example: under euler the 159 Hz tank decays to <2 V within ~13 periods; under trap it holds ≥4.25 V with the period exact to <2%.",
  ]),
  related: ['transient-analysis', 'capacitor-basics', 'inductor-basics'],
  seeAlso: ['convergence-issues'],
};

const smpsLayout: KBArticle = {
  id: 'smps-layout',
  title: 'SMPS Layout (Buck/Boost Switching Regulators)',
  category: 'pcb',
  tags: ['smps', 'buck', 'boost', 'switching', 'layout', 'emi', 'inductor', 'loop'],
  summary: 'Keep the hot switching loop (input cap → switch → inductor → output cap) as small as possible; ground the quiet analog section at one star point.',
  body: body([
    "# SMPS Layout",
    "",
    "## The Hot Loop",
    "",
    "Every switching cycle slams current through input-cap → high-side switch → inductor → output-cap. That loop radiates EMI proportional to its AREA — keep it under ~1 cm²: input ceramic within 2mm of the switch node, inductor adjacent, output ceramic at the inductor's far end.",
    "",
    "## Grounding",
    "",
    "One star point: power ground (switch + caps) meets analog ground (feedback divider) at exactly one via under the IC. Never route the feedback trace across the switch node.",
    "",
    "## Feedback",
    "",
    "Route FB as a short quiet pair from the output cap terminals (Kelvin), away from the inductor. Add 10–100pF feedforward across the upper divider resistor for phase margin.",
    "",
    "## Thermal",
    "",
    "Copper pours on the switch tab + thermal vias to inner planes. Size the inductor for <30% ripple at full load; check review.derating on the switch current.",
  ]),
  related: ['pcb-layout-basics', 'ground-plane', 'decoupling'],
  seeAlso: ['convergence-issues'],
};

const mcuFirmware: KBArticle = {
  id: 'mcu-firmware',
  title: 'MCU Firmware Bring-Up (Arduino/ESP32/Pi)',
  category: 'ic',
  tags: ['mcu', 'arduino', 'esp32', 'firmware', 'gpio', 'adc', 'pullup', 'decoupling'],
  summary: 'Decouple every supply pin (100nF), never float inputs, respect GPIO current limits (20mA AVR / 12mA ESP32), and bring up clock → GPIO → ADC → comms in that order.',
  body: body([
    "# MCU Firmware Bring-Up",
    "",
    "## Power First",
    "",
    "100nF ceramic on EVERY supply pin plus 10µF bulk nearby. Measure rails before inserting the MCU. Brown-out fuses on (AVR BOD 4.3V, ESP32 default).",
    "",
    "## GPIO Rules",
    "",
    "AVR: 20mA recommended / 40mA absolute per pin, 200mA total. ESP32: ~12mA per pin. Never drive a floating CMOS input — enable internal pull-ups or add 10k externals.",
    "",
    "## Bring-Up Order",
    "",
    "1. Clock (scope the crystal — sine ~1Vpp at rated freq). 2. Blink (GPIO toggle proves flash+clock). 3. UART hello. 4. ADC against known voltage. 5. Peripherals (I²C/SPI with pull-ups 2.2–4.7k).",
    "",
    "## Reset + Boot",
    "",
    "10k pull-up on RESET, 100nF to ground. ESP32: strapping pins (GPIO0/2/12/15) must be correct at reset or it won't boot — check review.checklist floating-inputs.",
  ]),
  related: ['555-timer', 'decoupling'],
  seeAlso: ['floating-node'],
};

const rfBasics: KBArticle = {
  id: 'rf-basics',
  title: 'RF Basics (Impedance, Transmission Lines, Antennas)',
  category: 'pcb',
  tags: ['rf', 'impedance', 'microstrip', 'antenna', 'matching', 's11', 'coplanar'],
  summary: 'Route RF as controlled-impedance (usually 50Ω) microstrip over unbroken ground; match source–line–load or power reflects (S11).',
  body: body([
    "# RF Basics",
    "",
    "## 50Ω Everywhere",
    "",
    "Antenna, feedline, and PA/LNA ports all want the same impedance (usually 50Ω). On 1.6mm FR4, 50Ω microstrip is ~2.9mm wide over full ground — use the stackup calculator, don't guess.",
    "",
    "## No Slots Under RF",
    "",
    "The return current flows directly under the trace. A slot or split forces a detour → inductance → ringing and radiation. See ground-plane.",
    "",
    "## Matching",
    "",
    "Measure S11 (return loss); add L-network (series L, shunt C) to pull the Smith-chart point to center. Simulate the match with acAnalysis before cutting copper.",
    "",
    "## Keep-Outs",
    "",
    "No copper, pour, or components under chip antennas (datasheet keep-out, typically 5×3mm+). Enclosure metal detunes — test in situ.",
  ]),
  related: ['pcb-layout-basics', 'ground-plane', 'ac-analysis'],
  seeAlso: ['decoupling'],
};

const esdSafety: KBArticle = {
  id: 'esd-safety',
  title: 'ESD + Electrical Safety (TVS, Creepage, Fusing)',
  category: 'troubleshooting',
  tags: ['esd', 'tvs', 'safety', 'creepage', 'fuse', 'iec', 'mains', 'protection'],
  summary: 'TVS diodes on every exposed connector (8kV contact per IEC 61000-4-2); mains needs fuse + MOV + ≥3mm creepage.',
  body: body([
    "# ESD + Electrical Safety",
    "",
    "## Exposed Interfaces",
    "",
    "USB/UART/buttons/antennas: unidirectional TVS to ground, <1pF for high-speed lines. Series 22–100Ω + TVS beats TVS alone (limits peak current).",
    "",
    "## Mains",
    "",
    "Fuse (slow-blow, rated 1.5× load) + MOV across L–N + Y-caps (Y1/Y2 rated) to PE. Creepage ≥3mm L–N, ≥6mm to touchable SELV. Double-check with review.checklist mains-fuse + esd-creepage.",
    "",
    "## Layout",
    "",
    "TVS ground via directly to chassis/ground pour (<2mm trace). No vias between connector pin and TVS — the strike must meet protection first.",
  ]),
  related: ['pcb-layout-basics'],
  seeAlso: ['parallel-voltage-sources'],
};

const jlcOrdering: KBArticle = {
  id: 'jlc-ordering',
  title: 'Ordering from JLCPCB / PCBWay (Gerbers, Assembly, PnP)',
  category: 'pcb',
  tags: ['jlc', 'pcbway', 'order', 'gerber', 'assembly', 'stencil', 'pnp', 'fab'],
  summary: 'Export the full fab bundle (copper + mask + paste + silk + Edge.Cuts + drill + PnP + BOM), pick the fab preset in DRC, and check rotation corrections before submitting.',
  body: body([
    "# Ordering from JLCPCB / PCBWay",
    "",
    "## What to Upload",
    "",
    "The fab bundle: top/bottom copper, solder mask, paste (stencil), silkscreen, Edge.Cuts outline, Excellon drill, pick-and-place CSV, and the BOM with LCSC numbers. This app's exportAllGerbers emits all of them plus a job file.",
    "",
    "## Before You Click Order",
    "",
    "1. DRC with the fab preset (JLCPCB 0.127mm / PCBWay 0.1524mm). 2. Waive reviewed items only. 3. Check PnP rotations (SOT-23/diodes need 180° — applied automatically here). 4. Confirm every BOM line has an LCSC number for assembly.",
    "",
    "## Stencil",
    "",
    "Order the paste stencil with the boards for SMD — 0.12mm stainless covers 0603+ fine. QFN/BGA wants 0.1mm + stepped apertures.",
  ]),
  related: ['pcb-layout-basics', 'ground-plane'],
  seeAlso: ['decoupling'],
};

// ─────────────────────────────────────────────────────────────────────────────
// ALL ARTICLES
// ─────────────────────────────────────────────────────────────────────────────

export const KB_ARTICLES: KBArticle[] = [
  // Concepts
  ohmsLaw,
  kvlKcl,
  voltageDivider,
  capacitorBasics,
  inductorBasics,
  // Semiconductors
  diodeBasics,
  ledCurrentLimiting,
  transistorBasics,
  mosfetBasics,
  // ICs
  opampBasics,
  timer555,
  // Troubleshooting
  floatingNode,
  missingGround,
  convergenceIssues,
  parallelVoltageSources,
  // Design patterns
  decoupling,
  transistorSwitch,
  flybackDiode,
  // PCB
  pcbLayoutBasics,
  groundPlane,
  smpsLayout,
  rfBasics,
  jlcOrdering,
  // Analysis
  dcOperatingPoint,
  acAnalysisArticle,
  transientAnalysis,
  behavioralSources,
  integrationMethods,
  // ICs (firmware)
  mcuFirmware,
  // Safety
  esdSafety,
];

// ─────────────────────────────────────────────────────────────────────────────
// SEARCH / LOOKUP
// ─────────────────────────────────────────────────────────────────────────────

export function getArticle(id: string): KBArticle | undefined {
  return KB_ARTICLES.find(a => a.id === id);
}

export function searchArticles(query: string, limit = 5): KBArticle[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  const words = q.split(/\s+/).filter(w => w.length > 2);
  const scored = KB_ARTICLES.map(article => {
    let score = 0;
    const haystack = (article.title + ' ' + article.summary + ' ' + article.tags.join(' ') + ' ' + article.body).toLowerCase();
    if (article.title.toLowerCase().includes(q)) score += 100;
    if (article.tags.some(t => t.toLowerCase() === q)) score += 80;
    if (article.summary.toLowerCase().includes(q)) score += 50;
    for (const word of words) {
      // Escape regex metacharacters — a query containing '(' or '[' would
      // otherwise throw SyntaxError and fail the whole kb.search call.
      const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const count = (haystack.match(new RegExp(escaped, 'g')) || []).length;
      score += count * 2;
    }
    return { article, score };
  });
  return scored
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(s => s.article);
}

export function getArticlesByCategory(category: KBArticle['category']): KBArticle[] {
  return KB_ARTICLES.filter(a => a.category === category);
}

export function getArticlesByTag(tag: string): KBArticle[] {
  return KB_ARTICLES.filter(a => a.tags.includes(tag));
}

export function getAllTags(): string[] {
  const set = new Set<string>();
  for (const a of KB_ARTICLES) {
    for (const t of a.tags) set.add(t);
  }
  return Array.from(set).sort();
}

export function getRelatedArticles(id: string): KBArticle[] {
  const article = getArticle(id);
  if (!article) return [];
  const related = article.related || [];
  const seeAlso = article.seeAlso || [];
  const allRelated = [...related, ...seeAlso];
  return allRelated
    .map(rid => getArticle(rid))
    .filter((a): a is KBArticle => a !== undefined);
}
