export function cleanupComponentState(sim: any, components: any[]): number {
  if (!sim || !sim.state || !sim.state.__global) return 0;
  const globalState = sim.state.__global; const validIds = new Set(components.map(c => c.id));
  let removed = 0; const keysToDelete: string[] = [];
  for (const key of Object.keys(globalState)) {
    const capMatch = key.match(/^cap_(.+?)(_i)?$/); if (capMatch) { if (!capMatch[1].match(/^\d+_\d+$/) && !validIds.has(capMatch[1])) { keysToDelete.push(key); removed++; } continue; }
    const indMatch = key.match(/^ind_(.+?)(_i)?$/); if (indMatch) { if (!indMatch[1].match(/^\d+_\d+$/) && !validIds.has(indMatch[1])) { keysToDelete.push(key); removed++; } continue; }
    const vcswMatch = key.match(/^vcsw_(.+)$/); if (vcswMatch) { if (!validIds.has(vcswMatch[1])) { keysToDelete.push(key); removed++; } continue; }
  }
  for (const key of keysToDelete) delete globalState[key];
  return removed;
}
export function compactTraces(traces: any[], maxSamples: number): number { let removed = 0; for (const t of traces) { if (t.samples.length > maxSamples) { const excess = t.samples.length - maxSamples; t.samples = t.samples.slice(-maxSamples); removed += excess; } } return removed; }
export function getMemoryStats(sim?: any, traces?: any[], components?: any[], wires?: any[]): any { const s: any = {}; if (typeof performance !== 'undefined' && (performance as any).memory) { s.usedJSHeapSize = (performance as any).memory.usedJSHeapSize; } if (typeof process !== 'undefined' && process.memoryUsage) { s.usedJSHeapSize = process.memoryUsage().heapUsed; } if (sim?.state?.__global) s.stateEntryCount = Object.keys(sim.state.__global).length; if (traces) s.totalTraceSamples = traces.reduce((sum: number, t: any) => sum + t.samples.length, 0); if (components) s.componentCount = components.length; if (wires) s.wireCount = wires.length; return s; }
export class MemoryMonitor { private snapshots: any[] = []; snapshot(sim?: any, traces?: any[], components?: any[], wires?: any[]) { const s = { timestamp: Date.now(), stats: getMemoryStats(sim, traces, components, wires) }; this.snapshots.push(s); if (this.snapshots.length > 100) this.snapshots.shift(); return s; } getSnapshots() { return [...this.snapshots]; } detectGrowth() { if (this.snapshots.length < 2) return 0; return (this.snapshots[this.snapshots.length-1].stats.usedJSHeapSize ?? 0) - (this.snapshots[0].stats.usedJSHeapSize ?? 0); } detectLeak(threshold: number = 10485760) { return this.detectGrowth() > threshold; } getSummary() { if (this.snapshots.length < 2) return { duration: 0, heapGrowth: 0, stateEntryGrowth: 0, traceSampleGrowth: 0, componentGrowth: 0, wireGrowth: 0, snapshots: this.snapshots.length }; const f = this.snapshots[0], l = this.snapshots[this.snapshots.length-1]; return { duration: l.timestamp - f.timestamp, heapGrowth: (l.stats.usedJSHeapSize ?? 0) - (f.stats.usedJSHeapSize ?? 0), stateEntryGrowth: (l.stats.stateEntryCount ?? 0) - (f.stats.stateEntryCount ?? 0), traceSampleGrowth: (l.stats.totalTraceSamples ?? 0) - (f.stats.totalTraceSamples ?? 0), componentGrowth: (l.stats.componentCount ?? 0) - (f.stats.componentCount ?? 0), wireGrowth: (l.stats.wireCount ?? 0) - (f.stats.wireCount ?? 0), snapshots: this.snapshots.length }; } reset() { this.snapshots = []; } }
export function suggestGC(): void { if (typeof globalThis !== 'undefined' && (globalThis as any).gc) (globalThis as any).gc(); }
export function resetComponentSimState(components: any[]): void { for (const c of components) c.simState = {}; }
